### ISSUE TITLE
Can't delete photos from the tree detail page

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-core#1091]
Users should be able to delete the photos they upload

**Comment by jwalgran** [comment]
Administrators should be able to delete any photo that may have been mistakenly approved during photo moderation.

**Comment by maurizi** [comment]
> Administrators should be able to delete any photo that may have been mistakenly approved during photo moderation.

Or we could instead add a separate tab(s) on photo review to look at photos that have already been accepted or rejected.

**Comment by dboyer** [comment]
I think these are two separate issues. Users should be able to delete their own photos from the tree detail page and admins should be able to delete any photo from the tree detail page. The separate tab for photos previously reviewed and either accepted/rejected seems like a different feature.

**Comment by RobinIsTheBird** [comment]
The design offered by @lederer:

A button styled the same as the Add Photo button appears on hover in the upper right corner of the large photo, if the user `can_delete` photos. Inside the button is no text, just a trash can icon. Clicking the trash can brings up a yes/no modal for confirmation. No dismisses it with no action. Yes deletes the photo.

**Comment by RickMohr** [comment]
:+1:

**Comment by dboyer** [comment]
Does large photo mean the larger of the two images always visible on the tree detail page (not the thumbnail) or does it mean the full size version of the photo that appears in a pop-up when you click the image?

**Comment by RobinIsTheBird** [comment]
@dboyer, the larger of the visible images.

There may be more than one thumbnail. You can upload multiple images.

**Comment by maurizi** [comment]
@RobinIsTheBird I think Deb was asking if the delete button would be on the visible on the main image when you load the page, or if you'd have to click on the image and delete it from the "image carousel" modal.

**Comment by RobinIsTheBird** [comment]
You'd have to get the image into the "image carousel" modal.

That is, the box that has the `Add Photo` button, left and right arrows, and the currently selected photo, would now also have a trash can button that appears only when hovering over that box.

**Comment by RobinIsTheBird** [comment]
@dboyer, if a user has permissions on all photo fields for a feature/plot, but isn't admin and isn't the original creator of the photo, should we allow them to delete the photo?

(We currently allow non-admin users to delete trees, plots, and features under the same circumstance.)

**Comment by RickMohr** [comment]
Since we plan soon to control deleting by specific "delete" permissions rather than the current "has permissions on all fields" strategy, I would vote to not worry about it.

**Comment by RobinIsTheBird** [comment]
@RickMohr,

Right now, editors by default get direct write permission on all photo fields, of which there aren't a whole lot. And there is no role management for setting photo field permissions.

Assuming that we really want to restrict who can delete a photo to the user that created it and an administrator (unless specifically permitted in the management console), we will not be able to merge this feature even if it passes review. It has to be marked as blocked.

Shall I mark it as blocked?

**Comment by RickMohr** [comment]
I see. I guess it depends on how much work it would be to add the "old-style" delete permissions, and if we're sure we will implement the direct permissions next sprint.

**Comment by jwalgran** [comment]
Users with management access can use `/{instance}/management/photo-review/` to effectively remove photos. In the short term, we could choose to only allow users to delete their own photos and then add the ability to delete other people's photos depending on role membership after implementing our expanded permission system.

**Comment by dboyer** [comment]
I am late to this, but I agree with jwalgran's above comment.
