### ISSUE TITLE
Clicking another dot in the green infrastructure detail page mini map hits a 404

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#1115]
Build 256 (OTM2_Build_Master) 2014-02-14_13-47-15
20d1dd655ce6892063bac00c5d978d2e8e458280 (OTM2)
664628cb453ed5552fcccdebb29d5876889e1642 (OTM2-tiler)
96d26b4b11197e784f54e1fbef5293c0e5d85e06 (OTM2-addons)
e69782ddcc639cc70ae1da4f8540280b5e018bdf (cloudbuild)

**Comment by steventlamb** [comment]
I cannot reproduce this. Perhaps it is fixed?

**Comment by jwalgran** [comment]
I can't reproduce it either.
