### ISSUE TITLE
Search box address not brought over from plot detail to map page

### ISSUE THREAD

**Issue by steventlamb** [OpenTreeMap/otm-core#1123]
After entering an address and selecting a geocoded location from the plot detail page, you are brought to the map page, but the address you entered is lost.

**Comment by jmorrison1847** [comment]
1. Go to a plot detail page in Philly Tree Map (https://www.opentreemap.org/phillytreemap/features/366764/)
![screen shot 2016-12-20 at 11 55 26 am](https://cloud.githubusercontent.com/assets/12401491/21359784/500e26f8-c6ab-11e6-9b4e-b82b38e2c632.png)

2. Enter an address (990 Spring Garden Street, Philadelphia) and pick the geocoded option from the dropdown menu
![screen shot 2016-12-20 at 11 55 46 am](https://cloud.githubusercontent.com/assets/12401491/21359789/565e29fe-c6ab-11e6-8c61-575daaf124d0.png)

3. Get sent to the approximate address on the map page but without the dropped pin and without the information stored in the search box
![screen shot 2016-12-20 at 11 55 54 am](https://cloud.githubusercontent.com/assets/12401491/21359890/b2c8a62e-c6ab-11e6-99d8-e716c9e0855b.png)
