### ISSUE TITLE
Species autocomplete issues

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#1179]
1) Type "a" and you see a completed tree name (e.g. "Alder") in the input box. 
2) Hit backspace. 

Problem #1: If you're in the "Search by Species" box or the "Plot detail" species box, the word "Alder" remains. (The "Add Tree" species box works correctly -- "Alder" disappears.)

3) Type "b"

Problem #2: no tree name appears in the input box.

These issues exist in production.

**Comment by jwalgran** [comment]
I cannot reproduce this on the current production release. Following the steps above works as expected

<img width="278" alt="screen shot 2016-03-31 at 11 07 41 am" src="https://cloud.githubusercontent.com/assets/17363/14185946/ee2b23fe-f730-11e5-9f3d-347f32b21fc8.png">
