### ISSUE TITLE
If no eco benefits for tree, need to add prompt to add details

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-core#1290]
Individual tree benefits are now visible thanks to #1086 

If the tree isn't generating benefits, we should show the same note we show on the tree detail page:

Add the diameter of the tree and select a species to calculate the yearly ecosystem services.

**Comment by jwalgran** [comment]
We now have prompts for different situations, and show the i-Tree region to instance managers to help with debugging.
