### ISSUE TITLE
User profile: top links incorrect

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#1325]
Log in, visit a map, and go to "My Account". The top links are "Explore Trees" and "Add a Tree", but:

* "Explore Trees" should be "Explore Map"
* "Add a Tree" should be "+" if the instance supports resources
* There should be a "Manage" link

**Comment by maurizi** [comment]
@dboyer Can we close this since it is working as intended?

**Comment by dboyer** [comment]
Yep
