### ISSUE TITLE
Advanced Search: Omit bottom line

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#1331]
When Advanced Search is open, can we consider omitting the bottom line (tree/plot/resource counts and add tree/resource buttons)?
* It could be confusing that the counts refer to your previous search, not the one you're configuring in the panel. For example, it might say "0 trees | 0 planting sites | 0 resources" after a restrictive search, and stay that way as you modify the search parameters.
* If you click "Add a Tree" does the advanced search pane disappear? Seems like the advanced search panel should behave more like a modal panel, where you have to explicitly click the "X" to dismiss it.
* The "Add" buttons are where I'd expect to see "Search" / "Cancel" buttons, which could cause mistakes

[Copied from an email thread. @dboyer replied "I'm fine with having the search results and add bar disappear while the advanced search filters are open. @mtedeschi  - any reason not to do that?"]

**Comment by maurizi** [comment]
This was done!
