### ISSUE TITLE
References to "beta access" in open source OTM2

### ISSUE THREAD

**Issue by andrewbt** [OpenTreeMap/otm-core#1390]
![beta_access_screen_in_open_source](https://cloud.githubusercontent.com/assets/2013555/3071079/059194aa-e2b2-11e3-99ca-800488646042.png)

I achieved this screen after using the activation link* that was sent to me after I made an account in my open source instance after applying @maurizi 's PR #1389. Clicking the button leads to http://localhost/beta/ which is a 404.

*link: http://localhost/accounts/activate/289f1800103459154ced114238e5b09b6d9e737a/

This may not be an issue, but it is odd that we would have references to the beta in the open source product.

**Comment by maurizi** [comment]
This ha been fixed
