### ISSUE TITLE
Add a form for resending activation emails

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#1424]
It should:
- Have a single field for email address
- On submit either: 
  - Say "that address is not registered" and link to the registration page 
  - Send a new registration email via `registration_profile.send_activation_email(site)`

**Comment by maurizi** [comment]
Support for this was added to django-registration-redux in version 1.3 (which we are now using) in the form of a `resend_activation_mail` function, so it should be easier to implement this than it was in past projects.

**Comment by hadleystein1** [comment]
+1

**Comment by dboyer** [comment]
Fixed.
