### ISSUE TITLE
Use parameterized raw query

### ISSUE THREAD

**Issue by steventlamb** [OpenTreeMap/otm-core#1442]
https://github.com/OpenTreeMap/OTM2/blob/7540ba5866d895e056ce250d286abf7cf704b2e5/opentreemap/treemap/audit.py#L68

Should this be:
```python
cursor.execute("select nextval('%s');", id_seq_name)
```
?

**Comment by maurizi** [comment]
Since `id_seq_name` comes from appending `_seq` to the table name and not from user input, this is not a vector for SQL injection.  I think we can close this.
