### ISSUE TITLE
"Add a Tree" button is enabled if user has write permission on any plot field

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#1545]
Log in to the dev server as a user with the "public" role for latreemap (don't use "administrator") and go to latreemap. You can click "Add a Tree" but you can't complete the process.

It looks like the "Add a Tree" button is enabled if the user has write permission on ANY plot field. They should need write permission on ALL plot fields.

Currently (to exercise this bug) the "public" role has write permission only on the "Address City" field.

**Comment by steventlamb** [comment]
potentially related: #2088

**Comment by maurizi** [comment]
I think we can close this now 😄
