### ISSUE TITLE
Comments over 3,000 chars produce error page when posted

### ISSUE THREAD

**Issue by andrewbt** [OpenTreeMap/otm-core#1642]
In Chrome 37:
1. Go to a tree detail page
2. Attempt to post a comment longer than 3000 characters
3. Notice the "upside down tree" error page

**Comment by maurizi** [comment]
I created an issue on the `django-contrib-comments` repo: https://github.com/django/django-contrib-comments/issues/80

**Comment by dboyer** [comment]
I cannot replicate this issue anymore.
