### ISSUE TITLE
Change default styling to show whether or not a plot contains a tree

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#1681]
We don't want to apply the old styling and suddenly turn Edmonton's map half orange, but this feature is missed. Maybe use dark green for trees and a lighter green for plots?

**Comment by jschmidt12** [comment]
I like the dark green for trees and light green for plots. I think this is something we should push up on the development list. It may become a feature Detroit is interested in.

**Comment by RickMohr** [comment]
When you do a search, features not included in the search results are shown in a lighter color. Whatever color scheme we choose we have to make sure you can tell the difference between a plot in the search results and a tree not in the search results.

**Comment by dboyer** [comment]
This can be part of implementing custom CartoCSS.

**Comment by jmorrison1847** [comment]
+1 from Rhody Trees; brown for the planting sites was their suggestion

**Comment by RobinIsTheBird** [comment]
Kelaine thought beige, Deb thought brown, need designer input.

**Comment by jwalgran** [comment]
We will likely need more agressive cache busting beacuase adding a tree to a planting site will change the color

**Comment by jwalgran** [comment]
We need to always join the tree table in tiler queries.

**Comment by dboyer** [comment]
@lederer We would like to change the dots indicating planting sites (no tree present) to be a different color than sites with trees. Could you suggest a color value? We were thinking some shade of brown/beige that would not distract from the green tree dots.

**Comment by andrewbt** [comment]
As we say in CARTO, vamos! 🇪🇸 👏

**Comment by lederer** [comment]
Great! I'll investigate and provide some color values.

**Comment by lederer** [comment]
I agree with @RickMohr's Mar 11 2015 comment that we should avoid using light green for planting sites iff we're rendering non-search results with a non-zero opacity.

Here are a few browns that should work well with the green markers without blending into common basemap colors:

1. #BCA371 (Wood Brown)
1. #7E6551 (Pastel Brown)
1. #664E4C (Medium Taupe)
1. #644536 (Van Dyke Brown)

They're listed in order of preference. Once someone has a demo running, it'd be great to see screenshots of all four using real data so we can compare.

**Comment by jmorrison1847** [comment]
I'm going to start trying to work in "Medium Taupe" to every day conversation.

**Comment by dboyer** [comment]
@lederer Planting sites are now in Wood Brown. Still your first choice for color?

![screen shot 2017-06-21 at 1 21 45 pm](https://user-images.githubusercontent.com/516764/27397533-a426bef8-5684-11e7-8d48-29728aa19bef.png)

**Comment by lederer** [comment]
LGTM

**Comment by jmorrison1847** [comment]
wow that looks awesome
