### ISSUE TITLE
Can't set the role for an invited user who does not yet have an account - should default to editor

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#1705]
We show a combo box to set the role, but there is no way to save it.

![screen shot 2014-10-08 at 1 52 46 pm](https://cloud.githubusercontent.com/assets/17363/4564020/fab4a2c4-4f13-11e4-9755-b55dfe8f52f0.png)

**Comment by maurizi** [comment]
This has been fixed
