### ISSUE TITLE
Creating a tree produces inconsistent state if cancelled and restarted

### ISSUE THREAD

**Issue by steventlamb** [OpenTreeMap/otm-core#1716]
test on staging. Steps to reproduce:
1. Start on an empty planting site
2. Click Edit
3. Click 'Add Tree'
4. Set a Species
5. Click 'Cancel'
6. Tree read info is present **[BUG]**
7. Click 'Edit'
8. Tree info is still there, but species is blank **[BUG]**
9. Click 'Save'
10. The UI indicates that species data exists **[BUG]**
11. Refresh the page.
12. There is no tree **[BUG]**

**Comment by dboyer** [comment]
Closing as I can no longer reproduce this bug.
