### ISSUE TITLE
Refresh all tree detail subsections when photos or inline edit form changes are saved

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#1719]
1. Create an empty plot and go to the detail page for that plot
2. Add a photo

Expected (and what appears after a page refresh):

![screen shot 2014-10-08 at 11 32 46 pm](https://cloud.githubusercontent.com/assets/17363/4570747/0445f38c-4f65-11e4-85e3-646eaeb7e48d.png)

Actual:

![screen shot 2014-10-08 at 11 32 31 pm](https://cloud.githubusercontent.com/assets/17363/4570755/1233dba8-4f65-11e4-8d3d-4b713b83c57f.png)

**Comment by RickMohr** [comment]
Problem still exists as described.
