### ISSUE TITLE
In an instance with all OTM species the species typeahead is too big for browser local storage

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#1857]
I made a treemap outside the US. Since it has no i-Tree region we initialize it with all known species.

Loading any page with a species typeahead gives this JS error (if you have the developer tools open):

    Uncaught QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of '__/edmonton2/species/__data' exceeded the quota.

The typeahead still works fine.

@maurizi suggests that we stop using browser-local storage for the typeahead species data and instead include it as a script tag on the page.

**Comment by RickMohr** [comment]
If we're not going to fix this in the short term we should at least catch the exception so that other code on the page still runs.

**Comment by maurizi** [comment]
We will also fix https://github.com/OpenTreeMap/otm-core/issues/199 as part of this.
