### ISSUE TITLE
Plot detail: Show i-Tree region and code

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#1907]
This would make it much easier to diagnose ecobenefits problems.

**Comment by RickMohr** [comment]
The eco section of plot detail can be formatted a few different ways:

![image](https://cloud.githubusercontent.com/assets/2162993/11666802/45b425e0-9dbc-11e5-809c-8e99c7f01c18.png)
![image](https://cloud.githubusercontent.com/assets/2162993/11666854/82eb38fe-9dbc-11e5-9d9b-1ac0303d4d93.png)

![image](https://cloud.githubusercontent.com/assets/2162993/11666829/67542812-9dbc-11e5-925d-e6fad23fa54a.png)

**Comment by RickMohr** [comment]
@dboyer, @designmatty, like either of these options?

**Comment by dboyer** [comment]
Either option is fine with me, but I think we should only display it for admins and super admins. It will be confusing to general users.

**Comment by designmatty** [comment]
I like option two. Seems a bit overkill to hide it within a modal.

**Comment by jwalgran** [comment]
I like showing the 2 additional rows in the yearly ecosystems services table.
