### ISSUE TITLE
No OTM install instructions for newer editions of Ubuntu

### ISSUE THREAD

**Issue by ghost** [OpenTreeMap/otm-core#1935]
"apt-get install postgresql postgresql-server-dev-9.1 postgresql-contrib postgresql-9.1-postgis-2.0" should use version 9.4 instead of 9.1

**Comment by jwalgran** [comment]
The installation guide wiki page has been updated for 64-bit Ubuntu 14.04

https://github.com/OpenTreeMap/otm-core/wiki/Installation-Guide
