### ISSUE TITLE
Posting an empty comment adds an empty UI element

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#1936]
It does not POST an empty comment to the server, but it does add extra form controls unnecessarily. 

![screen shot 2015-02-02 at 10 10 44 am](https://cloud.githubusercontent.com/assets/17363/6004955/f1350b9c-aac3-11e4-9909-5bbe4c238d98.png)

**Comment by maurizi** [comment]
We now prevent posting an empty comment, so I think we can close this
