### ISSUE TITLE
Switch from querying UDFs with 'udf:...' to using Django HStore's syntax

### ISSUE THREAD

**Issue by maurizi** [OpenTreeMap/otm-core#1968]
We currently use a custom syntax (e.g. `tree__udf:<UDF name>`) for querying UDF data.

This has caused issues for us (https://github.com/OpenTreeMap/OTM2/issues/1765) and we hade to blacklist certain characters, because Django is failing to parse our custom syntax when attempting to determine what the query is.

We would likely have to rewrite large portions of the code that provides our custom query syntax when switching to Django 1.7, so it makes more sense to switch to a well maintained external library instead.

We should switch to using Django HStore's syntax for querying hstore columns.  This would entail changing everywhere where we query with something like:

``` python
plots_funded_by_azavea = Plot.objects.filter('tree__udf:Funded By'='Azavea')
```

to instead look like this:

``` python
plots_funded_by_azavea = Plot.objects.filter('tree__udfs__contains'={'Funded By':'Azavea'})
```

**Comment by maurizi** [comment]
The custom `WhereNode` subclass we are using still works in Django 1.8, but it is deprecated and will be removed in 1.9.

Django 1.8 has support for [HStore as a contrib module](https://docs.djangoproject.com/en/1.8/ref/contrib/postgres/fields/#hstorefield), and supports a syntax _similar_ to what we are using now.  We may have a relatively easy upgrade path by moving from `django-hstore` to the builtin contrib.hstore

**Comment by maurizi** [comment]
Since this is a relatively large change, we might want to bite off the _even bigger_ change of switching from using an `hstore` column to store data to using  a `jsonb` column type.  There are many benefits of `jsonb` over `hstore`, and it seems like support for `hstore` will be declining in the future in favor of `jsonb`.

**Comment by RobinIsTheBird** [comment]
We should consider a suite of helper functions to provide a layer of abstraction. For instance, instead of
```
if model_name.startswith('udf:'):
```
write
```
from treemap.udf import is_model_udf
if is_model_udf(model):
```

OSLT.

**Comment by RobinIsTheBird** [comment]
I found 176 references to "udf:".
33 are in treemap.udf, which we would want to rewrite anyway.
123 are in tests.
That leaves only 20, distributed among 6 modules.

Seems to me like we could come up with a handful of abstractions to describe those 20 production uses outside treemap.udf, and allocate a "tech debt" issue to each abstraction. The issue would be done when all applicable production code has been changed to use the abstraction.

When all the production code uses abstractions, apply the abstractions to the test, and that clears the path to rewriting udfs on top of jsonb.

@maurizi , @jwalgran , @RickMohr , does that sound sufficient?

**Comment by RickMohr** [comment]
Sounds good to me.

**Comment by RobinIsTheBird** [comment]
It seems prudent to remove the unused `manage_treemap/partials/fields/udf_delete_popup.html`which must have been brought over at an ill-timed moment, as part of this issue. Mentioning it here to make sure to remember it.

**Comment by RobinIsTheBird** [comment]
@maurizi, @RickMohr, @jwalgran, the only use I can find of actually passing the `udf:` syntax to a query on a map feature or tree is in `search.py`. The rest of the `udf:` usage can be considered an interchange format.

Am I missing something?

If this is correct, then the only part that needs to change if we switch to the new contrib hstore module is the `search` parser, which dramatically reduces the scope of this issue.

Comments, please!

**Comment by jwalgran** [comment]
It makes sense that we would have centralized all of the code to convert OTM query JSON into QuerySet filters in a single place (or small number of places). 

I am not exactly sure what you mean by "interchange format." Are you stating that we don't have to change every place we use "udf:" in a field name because it is already being processed and converted when being transformed into a QuerySet filter? That makes sense.

**Comment by RobinIsTheBird** [comment]
@jwalgran, yes.

**Comment by RobinIsTheBird** [comment]
Okay, after
- reading and grepping
- instrumenting and poking in the UI
- asking colleagues,
I'm convinced that the use of `"udf:"` as part of a filter is in just one place in `search.py`, and that all others are what I'd call an interchange format or grammar for passing around references to udfs.

This issue is looking more like a 3 or a 5.

If there are tests for `"udf:"` style queries, they can either be thrown out or modified to use the new syntax.
