### ISSUE TITLE
Eco-benefits not updated after species import

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#1975]
1) Import a species with no i-Tree code.
2) Make a tree with that species. Note it has no eco-benefits.
3) Re-import the species, this time with an i-Tree code.

Expected: tree shows eco-benefits
Actual: tree still shows no eco-benefits

The problem is that the ecoservice is using stale cached data. We can fix it by hitting its `invalidate_cache` endpoint. But that's tricky in a multi-server environment.

**Comment by jwalgran** [comment]
Using the pub/sub built into redis may help us. When we import species, we can publish a message that all servers will receive and react to by invalidating their local cache.

**Comment by jwalgran** [comment]
http://redis.io/topics/pubsub

**Comment by RickMohr** [comment]
Moving to priority backlog because the sales team keeps hitting this.

**Comment by RickMohr** [comment]
Using pubsub looks straightforward, though it means running a persistent listener such as the thread in [this example](https://gist.github.com/jobliz/2596594)). We'd have to be confident the listeners would remain up, or else implement some kind of health check / restart logic.

Another option:
* add `instance.itree_override_rev`
* check it before any ecoservice call, and hit `invalidate_cache` if necessary

@jwalgran, thoughts?

**Comment by jwalgran** [comment]
I'd rather keep things simple and have the ecoservice check a `*_rev` value. It's proven to be both simple and successful in other contexts.

I agree that we need a more specific cache key. Is `itree_override_rev` too specific a name? Looking at the invalidate cacheFunction, maybe not. https://github.com/OpenTreeMap/otm-ecoservice/blob/ef31e3b4c53a203abd4057b53eac6d4329598bd7/ecorest/cache/main.go#L32-L64

**Comment by RickMohr** [comment]
Proposal:

* Note that the ecoservice caches i-Tree code overrides for all instances, and that invalidating the cache reloads overrides for all instances.
* We need a single `itree_code_override_rev` cache buster for all instances.
* There's currently no database table to store such a global value, so add a new model `treemap.Global` with an `itree_code_override_rev` field.
* When a Django app launches, store the current value of `Global.itree_code_override_rev` in a static `itree_code_override_rev` variable.
* When committing any `ITreeCodeOverride` change, increment `Global.itree_override_rev`.
* When making any ecoservice call, if `itree_code_override_rev` differs from `Global.itree_code_override_rev`, hit the ecoservice `invalidate_cache` endpoint and update the `itree_code_override_rev` variable.

@jwalgran, @maurizi, @RobinIsTheBird, comments?

**Comment by maurizi** [comment]
It might be simpler to store this `rev` value in Redis, rather than in the database.

**Comment by RickMohr** [comment]
Yes, that's better. And our Django integration does support increment (`incr`).
