### ISSUE TITLE
Windows 8.1 + IE 11 user redirected to "usupported" page during new account registration

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#1984]
![ie-11-redirected-to-unsupported](https://cloud.githubusercontent.com/assets/17363/6898749/a5ca5ad6-d6b0-11e4-95f7-3f63d38c2283.jpg)

**Comment by maurizi** [comment]
I could not replicate this on Windows 8.1 using IE11

**Comment by maurizi** [comment]
@dboyer @jmorrison1847 has anyone else reported this?  Can we close this issue?

**Comment by jmorrison1847** [comment]
I haven't heard any complaints related to this.
