### ISSUE TITLE
makemessages does not work with translation functions aliased to "trans"

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#1985]
See this SO answer: http://stackoverflow.com/a/16510454

The root of the problem is the fact that ``makemessages`` calls ``xgettext`` with a fixed set of "keywords." ``trans`` is not one of those keywords.

https://github.com/django/django/blob/master/django/core/management/commands/makemessages.py#L98

Identified by Filipe Marques and discussed on the opentreemap-user mailing list Mon, 30 Mar 2015 11:54:22

What is the tradeoff between switching to ``_`` vs switching to ``ugettrans/ugetrans_lazy``?

**Comment by RickMohr** [comment]
I propose using `_` instead of `trans` for translations, changing e.g. 
```py
header = trans('Tree Benefits')
```
to
```py
header = _('Tree Benefits')
```
Currently we use underscore (`_`) for unused variables; I propose changing to double underscore (`__`), so instead of
```py
_, field = pair.split('.')`
```
we would have
```py
__, field = pair.split('.')`
```
To me that looks better than the other alternatives I saw for unnamed variables:
```py
_model, field = pair.split('.')`
```
```py
unused_model, field = pair.split('.')`
```

**Comment by jwalgran** [comment]
Double underscore looks good to me.
