### ISSUE TITLE
Can't import CSV with Mac line endings

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#1998]
Error message is "new-line character seen in unquoted field - do you need to open the file in universal-newline mode?"

**Comment by jwalgran** [comment]
Are we talking about a file from classic Mac OS that has CR instead of LF endings? Do we have a sample file, or steps to reproduce?

The comments on the SO answer hint that CSVs saved by Excel may use CR. http://superuser.com/a/439443

**Comment by RickMohr** [comment]
I have a sample file but can't attach it to this issue and was hesitant to post an internal file path to a public repo. But here it is:

`\\fileshare\users\rmohr\bugs\OTM_Bulk_Uploader_Webinar.csv`

**Comment by jwalgran** [comment]
Looks like opening the file in ``'rU'`` mode may fix the issue

http://stackoverflow.com/questions/6726953/open-the-file-in-universal-newline-mode-using-csv-module-django
