### ISSUE TITLE
Importer: recover gracefully if subtask gets an exception

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#2025]
In the (unlikely) event of a subtask exception during an import, the import never completes.

We should detect the failure and report a status of something like "Verification Aborted" or "Creating Trees Aborted".

**Comment by steventlamb** [comment]
closing, covered by:
https://github.com/OpenTreeMap/otm-addons/issues/1045
https://github.com/OpenTreeMap/otm-core/issues/2452
