### ISSUE TITLE
Additional zoom levels available on Google satellite maps

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-core#2029]
An OTM user reported that standard Google Maps support zooming in an additional level as compared to OTM. Does the API not provide access to all zoom levels?

**Comment by steventlamb** [comment]
I was able to reproduce this. I can also confirm that google goes up to 21, and we have some code limiting our max zoom to 20. 

Related: https://github.com/OpenTreeMap/otm-core/commit/2627d145038d1b760066e32dce32414c8ef77f34

Should we bump it to 21?

**Comment by jwalgran** [comment]
I think bumping it up makes sense. I don't think there is a down side. We can use this as an opportunity to dry up the number of times we specify the max zoom.
