### ISSUE TITLE
Importer: "Cancel Import" doesn't work

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#2030]
Seen on the development server:

1) Create an instance centered on Edmonton
2) Do a tree import of \\fileshare\users\rmohr\notes\otm\importer\trees10k.csv
3) Once it starts, click "View" and "Cancel Import"

Expected: import is canceled.
Actual: import continues.

**Comment by jwalgran** [comment]
This may be a duplicate of https://github.com/OpenTreeMap/otm-core/issues/1980

**Comment by RickMohr** [comment]
Let's fix it.
