### ISSUE TITLE
Add polygonal map feature layer to the map page

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#2037]
Depends on https://github.com/OpenTreeMap/otm-tiler/issues/60

If the instance does not have polygonal map feature types, do not bother adding this layer to the map.

Coordinate min zoom level with the CartoCSS

**Comment by RickMohr** [comment]
Since this layer will only be shown at higher zoom levels and probably won't have many features we could consider using a GeoJSON layer instead of a tiled layer. Advantage -- fewer HTTP requests, faster load. Disadvantage -- requires custom implementation for mobile apps.

**Comment by maurizi** [comment]
@RickMohr I can't speak for how things are for iOS, but it looks like it's straightforward  to add a polygon to a Google Map on android (https://developers.google.com/android/reference/com/google/android/gms/maps/model/Polygon), but we'd have to write our own GeoJSON parser (thats not *too* hard though).

**Comment by jwalgran** [comment]
Creating tappable, polygonal overlays with iOS MapKit is possible.

https://developer.apple.com/library/ios/documentation/MapKit/Reference/MKPolyline_class/index.html#//apple_ref/occ/cl/MKPolyline

http://stackoverflow.com/questions/20858108/detecting-touches-on-mkoverlay-in-ios7-mkoverlayrenderer

http://stackoverflow.com/questions/4354130/how-to-determine-if-an-annotation-is-inside-of-mkpolygonview-ios

https://developer.apple.com/library/mac/documentation/GraphicsImaging/Reference/CGPath/index.html#//apple_ref/c/func/CGPathContainsPoint

http://stackoverflow.com/questions/19014926/detecting-a-point-in-a-mkpolygon-broke-with-ios7-cgpathcontainspoint

https://github.com/mattt/GeoJSONSerialization/

**Comment by jwalgran** [comment]
Working with vectors will requires performance tweaks sooner that raster tiles. Performance issues appear with thousands of vector features (hundreds on older IEs). It generally takes 10s of thousands of features before performance issues appear in raster layers.

In TreesCount we saw, when attempting to encode all the geometry in the UTF grid, that ST_AsGeoJSON start dominating the feature query time as the number of features increased.

Using an alternate renderer rules out unified styling of features. We plan to expose custom map feature styling options to map owners, so will need to restrict these options to a lowest common denominator supported by all three renderers (Leaflet, Android, iOS) and convert our style definitions to the syntax required for each of the renderers.

**Comment by maurizi** [comment]
@jwalgran Do we plan to offer anything more complex than "pick a fill/border color" for stormwater feature polygons?  If it is anything more complex than that I think we should favor raster tiles from Windshaft.

**Comment by jwalgran** [comment]
We have not yet discussed the map feature style customization use cases. They will be guiding our implementation of custom styles. Previous discussions have all been only mentioned color, but http://water.phila.gov/swexp/ makes good use of fill patterns to differentiate between the different polygon types.

**Comment by RickMohr** [comment]
Using a tile layer seems like the simpler and safer choice.
