### ISSUE TITLE
Header not working on Mobile?

### ISSUE THREAD

**Issue by collinanderson** [OpenTreeMap/otm-core#2039]
Hi All,

I just get a blank screen. No errors in the console. We're using the vagrant version. Any ideas?

Thanks,
Collin

**Comment by maurizi** [comment]
We don't have 100% support for mobile browsers, but you shouldn't be seeing a blank screen.

What phone/browser are you using?

**Comment by collinanderson** [comment]
Both Nexus 4 and iPhone 5. It's not 100% blank. It just doesn't have the header.

**Comment by collinanderson** [comment]
It looks like it just doesn't load the header, so there's no way to login.

![image](https://cloud.githubusercontent.com/assets/129234/8021015/df412758-0c5d-11e5-86f7-04faa113b1a5.png)

**Comment by maurizi** [comment]
Thanks for reporting this!

I've made a fix for this issue in https://github.com/OpenTreeMap/otm-core/pull/2055/.
