### ISSUE TITLE
Release: Cannot upload photo

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-core#2041]
On the LA test map on Firefox.

1. Login with public account. Public accounts have full write access to add photos.
2. Click "Add Photo" button
3. Nothing happens. 

This was testing in Chrome as well with both a public account and admin account. Photo uploads did not work.

**Comment by jwalgran** [comment]
I reproduced this. No JS errors in the console.

**Comment by steventlamb** [comment]
@dboyer you said "This was testing in Chrome as well with both a public account and admin account." Does that mean that you found this to be broken for admin accounts too?

I can reproduce with a public account, but not an admin account. It works fine for admin accounts. Was that the case for you?

**Comment by dboyer** [comment]
I should have been clearer. It didn't work when I tried with a super_admin account, but it did just work when I tried with the map owner account for that map.

**Comment by RickMohr** [comment]
I thought our policy was that super admins were granted read access but not write access.

In that case this would be as expected (unless the super admin was also a member of the tree map).

**Comment by dboyer** [comment]
In this case, the super admin was a member of the tree map.
