### ISSUE TITLE
Make `MapFeature` geometry-agnostic

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#2067]
Here's our current class hierarchy:

```
MapFeature (containing point field)
    Plot
    PolygonalMapFeature (containing polygon field)
        Bioswale
```

This has (at least) two problems:
1) `Bioswale` has a point field which it doesn't want
2) When the tiler renders map feature markers it always includes bioswales, even when bioswale polygons are also being rendered in another layer

Possible solutions to #2 include:
* In tiler SQL for rendering markers, exclude map features with polygons
* In tiler SQL for rendering markers, exclude map features whose type is not in `('Bioswale', 'RainGarden', ...)`

I don't like those solutions because the code for rendering markers has to consider everything that isn't a marker, which is fragile over the long-term.

I propose instead introducing a `PointMapFeature` class, making `MapFeature` geometry-agnostic:

```
MapFeature
    PointMapFeature (containing point field)
        Plot
    PolygonalMapFeature (containing polygon field)
        Bioswale
```

Advantages:
* `MapFeature` is geometry-agnostic; point features are no longer special
* Don't have to solve #1
* Straightforward solution to #2:
  * In tiler SQL for rendering markers, inner join to `treemap_pointmapfeature`
  * In carto CSS for polygonal map features, render a marker instead of a polygon below zoom 15

This would require a schema+data migration similar to [this one](https://github.com/OpenTreeMap/otm-core/blob/master/opentreemap/treemap/migrations/0055_auto__del_importevent__add_mapfeature__del_field_tree_import_event__de.py) but a bit more involved.

**Comment by maurizi** [comment]
-1.

The point feature on the bioswale model has proved useful in implementing advanced search, and I suspect will be useful in the future.

In terms of solving problem # 2 outlined above, I think the that their long-term fragility is not very significant, since I doubt we will accumulate a significant number of kinds of polygonal map features.
