### ISSUE TITLE
Return JSON error messages when there is an unhandled exception in an API request

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#2069]
The API sometimes returns HTML content when there is an error.

**Comment by maurizi** [comment]
@jwalgran does this bug include fixing this: https://github.com/OpenTreeMap/otm-core/blob/master/opentreemap/api/user.py#L103-L106?

Looks like we would need to make a few changes in the iOS application as well.

**Comment by jwalgran** [comment]
I don't think addressing that is a requirement for this issue. Returning a structured JSON body would require bumping the API version and doing a "translation" so that older app versions do not break.
