### ISSUE TITLE
Bioswale polygon is not greyed in advanced search, yet the corresponding point is

### ISSUE THREAD

**Issue by maurizi** [OpenTreeMap/otm-core#2093]

**Comment by maurizi** [comment]
This seems to only be intermittently hapening

**Comment by steventlamb** [comment]
@maurizi can you provide any more details? I can't reproduce this on staging or in development. I've tried the basics - Adding a tree, deleting a tree, zooming in and out, hard refreshing, restarting the tiler (dev only).

**Comment by maurizi** [comment]
@steventlamb I can't recall what seemed to be the cause of this, so feel free to close if you can't reproduce this.
