### ISSUE TITLE
Handle resource types without eco-benefits

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#2101]
A bioswale is a resource without eco-benefits. Things to fix:

1) A bioswale detail page should hide the "Ecosystem Benefits" section.

2) Bioswales shouldn't be included in the feature counts at the bottom of the eco-benefits summary on the map page. Here's what you get if your instance has only bioswale resources:

![image](https://cloud.githubusercontent.com/assets/2162993/8288720/e994dd3c-18e5-11e5-8f30-7bb96daeb4f0.png)

**Comment by dboyer** [comment]
Closing since bioswales can have ecobenefits now.
