### ISSUE TITLE
Bioswales not clickable with zoom >= 14

### ISSUE THREAD

**Issue by steventlamb** [OpenTreeMap/otm-core#2114]
Introduced by https://github.com/OpenTreeMap/otm-tiler/commit/f7f2f8754b7029f20f901ee72e677c1848418980

**Comment by maurizi** [comment]
Well the polygon should still be clickable right?

**Comment by RickMohr** [comment]
We need to either add a UTF grid for the polygon layer or add logic to select polygons server-side.
