### ISSUE TITLE
Show "trees within" on bioswale detail

### ISSUE THREAD

**Issue by steventlamb** [OpenTreeMap/otm-core#2122]
For this feature, as well as some others, it would make the most sense to put a class attribute on bioswale like `can_contain_trees` and then on any mapfeature subclass detail page, have a section like:
```
{% if feature.can_contain_trees %}
<h3>Trees within:</h3>
{% for tree in feature.trees_within %}
<a href="{{ tree.detail_page_url }}">{{ tree.id }}</a>
{% endfor %}
{% endif %}
```

This will need some design work, but it should be possible to get started.

**Comment by RickMohr** [comment]
If `can_contain_trees` were false

**Comment by maurizi** [comment]
It should be possible to reuse the existing styling of the page, in consultation with design.
