### ISSUE TITLE
Add fields to bioswale model

### ISSUE THREAD

**Issue by steventlamb** [OpenTreeMap/otm-core#2124]
date of installation
address: city/state/zip
length
width

The address/city/state/zip will not be populated by the polygon's geometry. They will just be text fields the user could complete but that would not cause the polygon to change.

**Comment by maurizi** [comment]
What is the reason for having a length/width in addition to a polygon?  It seems unnecessary to have both.

**Comment by steventlamb** [comment]
@dboyer are we assuming most bioswales will be parallelograms, or nearly so? Otherwise, length and width don't seem appropriate.

**Comment by RickMohr** [comment]
Address fields are already on the `MapFeature` model.
https://github.com/OpenTreeMap/otm-core/blob/master/opentreemap/treemap/models.py#L530-535

**Comment by RickMohr** [comment]
Date of installation might be better as a Gowanus UDF, unless we think every map including a bioswale will want that field.

**Comment by steventlamb** [comment]
@RickMohr there might be a clash between the behavior of the existing address fields, which are tied to the nearby address, and the custom address fields that the user may choose to enter. We need to clarify this.

**Comment by maurizi** [comment]
@steventlamb Address fields are filled in client-side via reverse geocoding, and are then user editable from the detail page.  We should be able to continue using them.

**Comment by dboyer** [comment]
For Gowanus, bioswales are always rectangles because they are built to a agreed upon specification. Length and width are intended to serve as a check on how the user drew the polygon. If the length and width seem very off, an editor may want to change the polygon. Updating the length and width should not impact the polygon.

**Comment by RickMohr** [comment]
We decided to implement these as custom fields. (See issue 500.) Closing

**Comment by steventlamb** [comment]
@RickMohr issue #500 appears unrelated to this feature.
