### ISSUE TITLE
Add support for perennial plants to bioswales

### ISSUE THREAD

**Issue by steventlamb** [OpenTreeMap/otm-core#2125]
Bioswales should have *some kind of* one-to-many relationship to perennial plants **species**, either using collection UDFs or traditional models.

We aren't keeping track of individual perennial plants in any way, simply listing zero or more species that are present within a bioswale.

Perennial plant choices will have to be editable by the instance owner.

Perennial Plants have some attributes, here's a preview:
![image](https://cloud.githubusercontent.com/assets/1699455/8463928/7142c500-200c-11e5-92c8-99e012581f8f.png)

**Comment by RickMohr** [comment]
It seems like using normal Django models will be a better fit than using UDFcs
