### ISSUE TITLE
Management: can't export comments

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#2145]
This is an issue on the development server but not in production.

1) Management > Comment Moderation > Export All

"There was an error while generating your export. Please try again later."

**Comment by maurizi** [comment]
I _was_ able to export comments using the `django-1.8` branch.

**Comment by RickMohr** [comment]
This failed with the `rick01` instance, but succeeded with the `latreemap` instance.

**Comment by RickMohr** [comment]
The celery log showed no entries in the failing case.

**Comment by RickMohr** [comment]
Wrong repo.
