### ISSUE TITLE
Add multichoice udf scalar type

### ISSUE THREAD

**Issue by steventlamb** [OpenTreeMap/otm-core#2152]

**Comment by steventlamb** [comment]
discussed with @ctaylo37, we'll use a 3rd party multiselect that supports typeaheads and inline "checking" selection.

**Comment by ctaylo37** [comment]
@steventlamb here is the multiselect we used for USACE:
https://github.com/davidstutz/bootstrap-multiselect

**Comment by maurizi** [comment]
@steventlamb Is this still blocked?
