### ISSUE TITLE
Release: Cannot save edits made in quick edit mode

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-core#2164]
On a test map that I created on June 24, I created a tree, viewed and edited on the detail page, and searched for it with no issues. I tried to edit the species and diameter using quick edit and get a red error bar under each field (see screenshot) with no error message when I click save.
![quick_edit](https://cloud.githubusercontent.com/assets/516764/8783584/d8a4ff00-2eea-11e5-88c3-74b11b167934.png)

**Comment by dboyer** [comment]
I cannot reliably reproduce this. It's happening occasionally but I don't see any pattern.

**Comment by maurizi** [comment]
Some errors in the JS console that may be related to this:
```
Uncaught RangeError: toFixed() digits argument must be between 0 and 20 treemap.min.js:22
```

**Comment by maurizi** [comment]
@dboyer Can you try retesting this?  I think this may have been caused by weird unit configurations on the LA map (tree diameter was set to show 100 digits)

**Comment by dboyer** [comment]
I can't replicate this so closing.
