### ISSUE TITLE
Bioswale does not have comment disclaimer text

### ISSUE THREAD

**Issue by steventlamb** [OpenTreeMap/otm-core#2172]
![screenshot from 2015-07-23 14 04 25](https://cloud.githubusercontent.com/assets/1699455/8858143/cfd3a24a-3143-11e5-9322-7c9ff2c19c88.png)

should look like:

![screenshot from 2015-07-23 14 05 13](https://cloud.githubusercontent.com/assets/1699455/8858156/dcae4ae2-3143-11e5-93af-30765a6ba75f.png)

**Comment by dboyer** [comment]
"a tree" should probably be replaced with either "a resource" or with whatever terminology the map owner sets.
