### ISSUE TITLE
Use non-field permissions for adding map features, deleting map features, and adding photos

### ISSUE THREAD

**Issue by maurizi** [OpenTreeMap/otm-core#2176]
Currently in order to have the ability to add a Tree you need to set "Full Write Access" permissions for "tree.id", "plot.id", and "plot.geom", which is not documented anywhere and is non-intuitive.  This is similar for adding a Plot.

Deleting is worse, you need to set "Full Write Access" on _all_ fields in order to be able to delete a plot or tree.

For photo permissions the UI shows a single "Photo" checkbox, but in the backend we turn that into field permissions for each individual photo field, which is not ideal.

I propose we stop using field-level permissions for these actions, and instead use model-level permissions using the [built-in Django permissions](https://docs.djangoproject.com/en/1.8/ref/contrib/auth/#permission).

**Comment by jwalgran** [comment]
Can you elaborate on how we would use Django ``Permission`` objects in our multi-tenant system. Do we embed the instance ID in the ``code_name``? Use a subclass with an additional ``instance_id`` column?

**Comment by maurizi** [comment]
We could add a OneToMany field on Role, or we could subclass Permission.  Or we could roll our own thing if the built-in class isn't featureful enough for us.  I would go with option 1 if possible.

**Comment by maurizi** [comment]
It looks like the built-in `Permission` [has a uniqueness constraint that might hamper using it](https://github.com/django/django/blob/master/django/contrib/auth/models.py#L73).

Regardless, I think it would be a good idea to use model-level permissions for some of these actions that are not really field-specific, instead of over-relying on our `FieldPermission` code.

**Comment by steventlamb** [comment]
@maurizi would the uniqueness constraint actually be a problem if we always proxy the perm through the role, which we mostly (or entirely) do already? Example psuedocode:

```
i1 = Instance(...)
i2 = Instance(...)
plot_delete = Permission(code_name='plot_delete', content_type=<...plot...>)
i1.default_role().model_permissions.add(plot_delete)
i2.default_role().model_permissions.add(plot_delete)
```
Just because they point to the same perm doesn't mean they can't validate the instance too.

**Comment by maurizi** [comment]
@steventlamb Thats true, we could have instances share permission rows.  If we go this way, then a user was permission to delete a plot if their role has a FK to a `plot_delete` row?  Makes sense to me.

**Comment by RickMohr** [comment]
+1. So just a few singleton Django `Permission` objects, and `ModelPermission` is a join table for `Role` and `Permission`.

**Comment by RickMohr** [comment]
We also agreed in discusion to remove the ability to set location (geom), species, or diameter to "Invisible." (See https://github.com/OpenTreeMap/otm-addons/issues/1005)

**Comment by maurizi** [comment]
We talked about this a bit.

We are interesting in pursuing using the built-in `Permission` model in Django.

We will create a fixed number of "Singleton" rows in the database, and will create a `ManyToMany` field on `Role` that points to `Permission`.

Our plan is to create a set of "Add", "Delete", "Add Photo", and "Delete Photo" permissions per `MapFeature` model.
Determining if a user has permission to do an action on a specific `Instance` will entail looking up their `Role`, and if the Role has that permission, they are allowed to do the action.  We considered using the `Group` model also built-in to Django, but this does not allow us to tie to the `Instance`.

Additionally, we will identify fields that are required to be writeable in order to create the model (such as `Plot.geom` and the `id` fields).  These fields will be _removed_ from the existing `FieldPermission` system (but still trackable), and any existing UI interactions which require those fields to be writeable will be changed to use Model-level permissions (e.x. `can_move_plot_location`).

![img_20160929_154730](https://cloud.githubusercontent.com/assets/4432106/18970333/dd96a44c-865e-11e6-8065-c29c9ea97699.jpg)

**Comment by RobinIsTheBird** [comment]
Remember to remove field permissions entirely from `TreePhoto` and `MapFeaturePhoto`.

**Comment by RobinIsTheBird** [comment]
@jwalgran , @maurizi , @RickMohr , should I make `Tree.species` always readable/writable?

**Comment by jwalgran** [comment]
I think no for two reasons:

- Species is not a required field.
- Species is something that is difficult for laypeople to identify, so map owners may want to restrict the editability.

**Comment by RickMohr** [comment]
Note -- there should be no field permission for `PolygonalMapFeature.polygon` (i.e. it should be in `_always_writable`)
