### ISSUE TITLE
Photo and Geometry permissions should default to read-only, not invisible

### ISSUE THREAD

**Issue by maurizi** [OpenTreeMap/otm-core#2177]
Even if the default permission for the role is invisible, these permissions should only have the options of "Read Only" or "Full Write Access"

**Comment by maurizi** [comment]
Possibly this would be true for a few other fields as well?  Definitely for `id` for various models.  Species comes to mind as well - we always show the species search box, even if species is marked as invisible.

**Comment by RickMohr** [comment]
This is handled now that we have explicit add/delete permissions -- geom and photos no longer use field permissions.
