### ISSUE TITLE
The login link on the comments section should redirect back to the feature detail page

### ISSUE THREAD

**Issue by maurizi** [OpenTreeMap/otm-core#2185]
When not logged in, the plot detail page shows:

![image](https://cloud.githubusercontent.com/assets/2162993/18725967/636ad57a-8010-11e6-8350-00ed81aaf031.png)

**Comment by jwalgran** [comment]
Related to https://github.com/OpenTreeMap/otm-core/issues/2239

**Comment by RickMohr** [comment]
Blocked until #2239 is fixed

**Comment by maurizi** [comment]
@RickMohr I believe this is unrelated to https://github.com/OpenTreeMap/otm-core/issues/2239.

**Comment by RobinIsTheBird** [comment]
@maurizi, oth, some utility work for #2239 may come in handy in fixing this one.
