### ISSUE TITLE
Individual "Tree Benefits" Do Not Appear on Rhodytrees Map

### ISSUE THREAD

**Issue by jmorrison1847** [OpenTreeMap/otm-core#2191]
The total eco benefits are calculated based on 5,229 out of 5,420 trees. But when you click on the individual trees (almost all have both species and diameter) you never get the isolated eco benefits of that tree. And when you go into the details page, it has a message at the bottom requesting the the user to "Add the diameter of the tree and select a species to calculate the yearly ecosystem services.” Here’s an example: https://www.opentreemap.org/rhodytrees/features/661281/

**Comment by dboyer** [comment]
Duplicate with issue in another repo.
