### ISSUE TITLE
Add RainBarrel GSI model

### ISSUE THREAD

**Issue by steventlamb** [OpenTreeMap/otm-core#2215]
As a PointMapFeature, with *some* of the following as default / non-udf fields:
* capacity
* is_self_draining
* shape / dimensions / height / circumference
* material (plastic, terra cotta, etc.)

**Comment by RickMohr** [comment]
LA's rain barrel has a field for "drains to pervious vs. impervious".

**Comment by dboyer** [comment]
Let's set capacity as the only default field. The other options seem useful, but in my research, it looks like capacity is the only key item.

**Comment by jwalgran** [comment]
"Capacity" should probably tied into the units system, so it can be set to display as gallons or liters (like the stormwater eco benefit)

**Comment by steventlamb** [comment]
To be complete, this will require:
* adding support for units to other models (including this one)
* making it possible to customize the step count for resources during the add map feature process
