### ISSUE TITLE
Add a revision counter for use with eco benefits

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#2260]
We want to start caching the JSON responses from the eco service. To do that we need a cache key that changes whenever an eco related attribute changes.

This also includes checking the cache before making a request to the ecoservice.

**Comment by jwalgran** [comment]
In addition to the places where we invalidate the georev, we want to invalidate when there are changes to super_admin change to the region or a species import.

**Comment by RickMohr** [comment]
Blocked behind #2256. (Can't cache things before the cache is set up.)

**Comment by jwalgran** [comment]
I don’t think the built-in versioning system applies in this situation, given our multi-tenant situation, but it is worth reviewing this section.
https://docs.djangoproject.com/en/1.8/topics/cache/#cache-versioning
