### ISSUE TITLE
Review release notes for Python dependency updates and apply/defer them

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#2266]
The requires.io service opened a pull request https://github.com/OpenTreeMap/otm-core/pull/2255

We need to review what is included in these updates and allocate time for dealing with breaking changes.

**Comment by maurizi** [comment]
I contacted support for requires.io and they recommended we deal with the "non-release" of modgrammar-py2 by changing the line in our `requirements.txt` to be:
`modgrammar-py2==0.9.1 # rq.filter: !=0.9.2`
