### ISSUE TITLE
Comment Moderation notification bubbles persist indefinitely unless archived

### ISSUE THREAD

**Issue by jmorrison1847** [OpenTreeMap/otm-core#2331]
I made three comments:
![screen shot 2015-10-29 at 5 21 57 pm](https://cloud.githubusercontent.com/assets/12401491/10832474/1048252e-7e62-11e5-907b-1ff0a60ce977.png)
Then I archived one and the notification bubble on Comments went from "3" to "2".
![screen shot 2015-10-29 at 5 22 53 pm](https://cloud.githubusercontent.com/assets/12401491/10832487/214bfad0-7e62-11e5-9d98-1dff71a45a6e.png)
But once I "unarchived" it, the notification bubble returned to the state of "3" comment (presumably that need attention.
![screen shot 2015-10-29 at 5 23 17 pm](https://cloud.githubusercontent.com/assets/12401491/10832517/499ea03c-7e62-11e5-8428-2c7ef075fb27.png)

There should be a way to get rid of those notification bubbles, either passively or actively, without having to archive them. The act of looking at them on the page should probably remove the notification bubbles, but the alternative would be an "approve" button that actively gets rid of the notification bubbles for comments that you affirm.

**Comment by maurizi** [comment]
This is in the wrong repository
