### ISSUE TITLE
Loading spinner appears jagged on white background

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#2335]
We changed the spinner in #2309 to be compatible with light and dark background but it looks pretty jagged against a white background

<img width="285" alt="screen shot 2015-11-03 at 9 11 15 am" src="https://cloud.githubusercontent.com/assets/17363/10913432/1e23f8ce-820b-11e5-8d13-b9c6fb5dc978.png">

**Comment by RickMohr** [comment]
@jwalgran, in practice I think it looks fine, propose we close this.

**Comment by designmatty** [comment]
We could in theory switch to using an svg or font icon. The downside is this would require a bit more markup and bit more css. We might also break the look for our users that rock old browsers.

**Comment by jwalgran** [comment]
I would still like to improve the appearance of the spinner.

The "halo" method described on http://spiffygif.com/docs/ is a possible, low-tech compromise.

**Comment by RickMohr** [comment]
+1 :angel:

**Comment by designmatty** [comment]
oh nice find! We should just download the spiffygif from here and implement. http://spiffygif.com/?color=858585&halo=true

**Comment by designmatty** [comment]
![spiffygif_32x32](https://cloud.githubusercontent.com/assets/1928955/14994352/7a3f899a-113d-11e6-8dd6-f9f277aadb7f.gif)

**Comment by designmatty** [comment]
it honestly still looks jagged: 

<img width="293" alt="screen shot 2016-05-03 at 2 55 14 pm" src="https://cloud.githubusercontent.com/assets/1928955/14994687/38af3582-113f-11e6-8078-139f36d471be.png">

**Comment by designmatty** [comment]
Nevermind. I realized how to fix that issue. Will make a PR soon
