### ISSUE TITLE
Add Rollbar integration for client-side JS errors.

### ISSUE THREAD

**Issue by maurizi** [OpenTreeMap/otm-core#2343]
I'm labeling this as `question` because I'm not sure if this is something we want to track, but it seems like a good idea.

**Comment by jwalgran** [comment]
+1

**Comment by jwalgran** [comment]
The team decided yes, we do want to implement this.

**Comment by RobinIsTheBird** [comment]
Does this issue cover only uncaught errors, or does it also cover looking for places we might want to explicitly log at some level?

**Comment by maurizi** [comment]
I vote for only uncaught exceptions.

**Comment by jwalgran** [comment]
This is the first step, just setting up unhandled exception tracking.
