### ISSUE TITLE
UI: "View All Details" and "Full Details" are identical links

### ISSUE THREAD

**Issue by jmorrison1847** [OpenTreeMap/otm-core#2345]
For simplicity sake, perhaps they should be consistently named since they often appear on the same page when a user clicks a tree or planting site from the map page.
![screen shot 2015-11-09 at 9 23 13 am](https://cloud.githubusercontent.com/assets/12401491/11037587/78e6005c-86cc-11e5-8091-6f8642a9c799.png)

"Edit Details" and "Quick Edit" have different text but signify different actions/workflows.

**Comment by dboyer** [comment]
Let's go with View All Details.

**Comment by lederer** [comment]
Saw this mentioned in slack… 

+1 to consistent labels.

I'd say the general lingo these days would skew toward "More details" for that one.

While we're at it, the edit button could be changed to simply "Edit". That would eliminate the multiple "details" across adjacent buttons, which could add some cognitive load to recognizing the right button.

**Comment by dboyer** [comment]
I'm good with "More Details" and "Edit" but would like to keep "Quick Edit" to show that it is a different editing feature than the full Edit.

**Comment by lederer** [comment]
That makes sense.
