### ISSUE TITLE
Use current location (browser)

### ISSUE THREAD

**Issue by jmorrison1847** [OpenTreeMap/otm-core#2347]
As a step towards a hybrid app/for users that use a tablet with a browser open to the web app, the ability to "use current location" (center map on GPS location, just like the native apps) would be a very useful feature.

**Comment by dboyer** [comment]
@jmorrison1847 There is an option to use current location when adding a tree on the OTM website (not the app). Do you mean a general "use my location" as a search option?

**Comment by jmorrison1847** [comment]
@dboyer I never noticed that, thank you very much!
