### ISSUE TITLE
Remove extra items in Google Street View box

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-core#2364]
Looks like the Google Street View box changed again and the amount of overlay material (info box, directional, etc) makes it difficult to actually see the image. Can we minimize the info box and perhaps remove the circular rotation and full screen boxes?
![streetview](https://cloud.githubusercontent.com/assets/516764/11541141/9de66678-98fe-11e5-87c1-c5be14fbf07a.png)

**Comment by jwalgran** [comment]
It looks like there are some more options that we pass to the `StreetViewPanorama` constructor to disable some widgets

Example from https://developers.google.com/maps/documentation/javascript/examples/streetview-controls

```javascript
 var panorama = new google.maps.StreetViewPanorama(
      document.getElementById('map'), {
        position: {lat: 42.345573, lng: -71.098326},
        addressControlOptions: {
          position: google.maps.ControlPosition.BOTTOM_CENTER
        },
        linksControl: false,
        panControl: false,
        enableCloseButton: false
  });
