### ISSUE TITLE
Staging: Missing photos search not accurate

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-core#2428]
Tested on testmap0111

1. The map has 6 trees and 7 planting sites 
2. I checked the missing photos box
3. The search results say 6 trees and 7 planting sites but there are at least three that have photos

**Comment by steventlamb** [comment]
I cannot reproduce this on https://staging.opentreemap.org/testmap0111/map/?q=%7B%22mapFeaturePhoto.id%22%3A%7B%22ISNULL%22%3Atrue%7D%7D

I get 3 trees and 4 planting sites, consistent with your description. Is it possible you had some other filters active at the time?

If the benefit/counts portion of the search crashes, you will see no feedback and your counts will remain the same. If you had other filters in conjunction with missing photo that together produced a crash, it could have caused this.

**Comment by dboyer** [comment]
I can't reproduce this either so closing.
