### ISSUE TITLE
Add Tree validation error appear in confusing blue well

### ISSUE THREAD

**Issue by steventlamb** [OpenTreeMap/otm-core#2429]
Only the first well here should be blue. Red, yellow or orange is called for.
![screenshot from 2016-01-11 16 27 28](https://cloud.githubusercontent.com/assets/1699455/12247086/441a1fa8-b880-11e5-8cac-67104f9bad01.png)

**Comment by jwalgran** [comment]
This is a validation error so, for consistency, I think it should be "danger" red.
