### ISSUE TITLE
Long usernames wrap or overlap content on the user profile

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#2438]
Long usernames with hyphens overlap themselves 

<img width="244" alt="screen shot 2016-01-12 at 7 05 11 pm" src="https://cloud.githubusercontent.com/assets/17363/12282944/9ff8f26a-b95f-11e5-9f1a-a38a3cfc234d.png">

Long usernames without hyphens overlap other content 

<img width="945" alt="screen shot 2016-04-01 at 9 39 13 am" src="https://cloud.githubusercontent.com/assets/17363/14213597/b095e75a-f7ed-11e5-9706-287f948ba5b1.png">

**Comment by designmatty** [comment]
Which fix would you guys prefer:
1: 
<img width="331" alt="screen shot 2016-05-03 at 10 07 03 am" src="https://cloud.githubusercontent.com/assets/1928955/14985747/dc12b088-1116-11e6-85a7-e1f568841f56.png">

2: 
<img width="375" alt="screen shot 2016-05-03 at 10 06 42 am" src="https://cloud.githubusercontent.com/assets/1928955/14985753/e158e3e6-1116-11e6-98ec-5eecc8663177.png">

**Comment by RickMohr** [comment]
I vote wrap (#2) since there's plenty of space on the user profile page.

**Comment by jwalgran** [comment]
+1 to wrapping rather than truncating

**Comment by dboyer** [comment]
Agreed with wrapping.

**Comment by designmatty** [comment]
Sounds good. I'll make sure this get done
