### ISSUE TITLE
When loading the import status page, check Celery to determine if a job has failed

### ISSUE THREAD

**Issue by maurizi** [OpenTreeMap/otm-core#2452]
If an importer fails while still in progress, we never change its status to failed.

Since we record Celery task IDs, we can query Celery to see if the tasks for a import job still exist, and if none are present, mark the job as failed.

**Comment by RickMohr** [comment]
We never discussed what user-visible changes this work should aim to support. Please see proposal at OpenTreeMap/otm-addons#1045

**Comment by steventlamb** [comment]
We discussed this today and decided that we will use two criteria for determining if a job is in a failed state:
1) the status of the celery `AsyncResult`
2) A newly introduced `processed_at` field on `ImportEvent` models that will have a time logged every time a related `ImportRow` performs work asynchronously and will be cleared/nulled when the import is complete.

Any `ImportEvent` that has a failed `AsyncResult` or an old value (where old >= 30 minutes) in `processed_at` will be considered stuck/lost and modified accordingly (a new boolean field on `ImportEvent`, `is_lost`). This was decided, for the time being, to be used lieu of making tasks idempotent and using `ACKS_LATE` or timeouts in celery.

When we add support for resumption, we will make these import events available in the ui.

**Comment by RickMohr** [comment]
Thanks for the summary. Consider naming the heartbeat field `row_processed_at`.

**Comment by jwalgran** [comment]
row_processed_at is a good, literal name

**Comment by steventlamb** [comment]
thanks for the feedback. row_processed_at > processed_at. However, is `last_row_processed_at` even better?

**Comment by RickMohr** [comment]
`row_last_processed_at`
