### ISSUE TITLE
Some maps not loading tree and planting site numbers or advanced search bar

### ISSUE THREAD

**Issue by hadleystein1** [OpenTreeMap/otm-core#2454]
Problem yesterday afternoon and this morning with maps not properly loading. In the case of this trial map (https://www.opentreemap.org/montrealbgtrees/map/) the page loads, however, the following information is missing.
- No information on total number of trees or planting sites (first screenshot)
- Advanced search bar not formatted or working properly (first screenshot)
- Tree dots do not appear until you zoom in closer to their location (second screenshot)

Refreshing the webpage and/or closing Chrome and reloading do not seem to fix the problem. With that said, the problem seems to be limited to certain maps and certain computers. Attempted to open the map on other computers seems to work fine.

![screen shot 2016-01-15 at 10 38 24 am](https://cloud.githubusercontent.com/assets/15219245/12357212/a071e2f8-bb74-11e5-899b-d77cb910a91e.png)
![screen shot 2016-01-15 at 10 39 04 am](https://cloud.githubusercontent.com/assets/15219245/12357214/a3e0d96c-bb74-11e5-9a3d-177998befaf0.png)

**Comment by jwalgran** [comment]
Based on the screenshots and descriptions I suspect that this is because the browser is loading a cached copy of an old page style. If you hold the the Shift key while clicking the Reload button, does that resolve the issue?

**Comment by hadleystein1** [comment]
Yes, thanks @jwalgran. The problem is solved.

**Comment by jwalgran** [comment]
We would like to make some developer tooling upgrades in the future that would eliminate the need to do this, but we do not yet have a timeline for those changes.
