### ISSUE TITLE
Regression (staging): "Search" button mis-located in "Add a Tree" sidebar

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#2478]
In production the "Search" button is fine but on staging it wraps below the input box:

![image](https://cloud.githubusercontent.com/assets/2162993/12655101/51ee2a78-c5c5-11e5-983f-b614fd3f4520.png)

**Comment by RickMohr** [comment]
@steventlamb, FYI @maurizi thought he fixed this but might have lost it in a rebase

**Comment by jwalgran** [comment]
Changing the milestone because 2.2 was released last week.

**Comment by RickMohr** [comment]
This did make it into 2.2.0, via #2482

**Comment by jwalgran** [comment]
Sorry about the overly aggressive cleanup
