### ISSUE TITLE
Queries to updating TreeImportEvent during an import can take over 10 seconds to complete

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#2500]
During isolated, single-user testing of tree imports we logged database update queries taking over 10 seconds. A normalized example:

```
UPDATE "importer_treeimportevent"
SET
    "file_name" = '',
    "errors" = '',
    "field_order" = '',
    "owner_id" = 0,
    "instance_id" = 0,
    "created" = '' ::timestamptz,
    "completed" = NULL,
    "status" = 0,
    "last_processed_at" = '' ::timestamptz,
    "is_lost" = FALSE,
    "task_id" = '',
    "plot_length_conversion_factor" = 0.0,
    "plot_width_conversion_factor" = 0.0,
    "diameter_conversion_factor" = 0.0,
    "tree_height_conversion_factor" = 0.0,
    "canopy_height_conversion_factor" = 0.0
WHERE
    "importer_treeimportevent"."id" = 0;
```

We suspect long running transactions may be blocking updates, possibly related to the high frequency at which we are updating `last_processed_at` while an import is in progress.

**Comment by hectcastro** [comment]
Raw PostgreSQL logs, along with the pgBadger processed report:

- [postgresql.log.2016-02-09-03.zip](https://github.com/OpenTreeMap/otm-core/files/123904/postgresql.log.2016-02-09-03.zip)
- [postgresql.log.2016-02-09-04.zip](https://github.com/OpenTreeMap/otm-core/files/123905/postgresql.log.2016-02-09-04.zip)
- [pgbadger.html.zip](https://github.com/OpenTreeMap/otm-core/files/123906/pgbadger.html.zip)

**Comment by steventlamb** [comment]
Our best guess so far is that `commit_rows` should not be wrapped with `transaction.atomic`, only `commit_row` should be.

**Comment by RickMohr** [comment]
Also, we update `last_processed_at` for every row, for crash detection. It would be just as effective to update it only at the end of a chunk of rows.
