### ISSUE TITLE
Create proposal for importer, exporter and presentation field names

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#2504]
The result of this task should be a table with proposed field names for:
* csv exports
* bulk uploader import templates
* management site columns

Some investigation should go into:
* whether case sensitivity will be an issue in processing input
* conditional exclusion of model prefix based on the context
* fields that should be removed (tree ID)
* fields that should be renamed (plot -> planting site)

**Comment by steventlamb** [comment]
Case sensitivity will not be an issue. The importer is very lenient. I made a udf called 'TheNum', and the following csv imports correctly and makes a plot with a val for "TheNum":
```
poiNt x,poInt y,plot: THeNum
-101.665420332,33.6443490445,3
```

General Strategies:
As discussed, there is no benefit to having database-style column headers in any CSV. Given that the importer handles spaces and case well enough, it makes sense to use similar, nicely formatted names everywhere. The exporter is flexible in how it handles changes to column headers, so this will not be difficult.
In general, Plot should be renamed to planting site in all cases.
Readability is lost if you remove model prefixes. For example 'Planting Site Length' makes more sense than 'Length'. The exporter and importer should have identical column headers, but it's fine for mgmt pages to remove the prefix when it is part of a model-specific table.

| tree export                  | import template     | mgmt           | plan                                                                                     |
| ------------------------------|---------------------|----------------|------------------------------------------------------------------------------------------|
| plot__geom__x                | Point X             | Geom           | Don't merge, go with 'Point X'                                                           |
| plot__geom__y                | Point Y             | Geom           | Don't merge, go with 'Point Y'                                                           |
| date_removed                 |                     | Date Removed   | Date Removed, add to import template                                                     |
| date_planted                 | Date Planted        | Date Planted   | Date Planted                                                                             |
| diameter                     | Diameter            | Diameter       | Diameter                                                                                 |
| plot__width                  | Plot Width          | Width          | Planting Site Width                                                                      |
| plot__id                     |                     | Plot (also Id) | Don't fully merge                                                                        |
| plot__length                 | Plot Length         | Length         | Planting Site Length                                                                     |
| species__cultivar            | Cultivar            |                | Cultivar                                                                                 |
| plot__readonly               |                     | Readonly       | ? This is a tough one, hard to differentiate model without banging into UDF recognition. |
| readonly                     |                     | Readonly       | ? This is a tough one, hard to differentiate model without banging into UDF recognition. |
| height                       | Tree Height         | Height         | Tree Height                                                                              |
| id                           | OpenTreeMap Plot ID | Id             | Remove from import/export                                                                |
| species                      | Species             | Species        | Species                                                                                  |
| species__common_name         | Common Name         |                | Common Name                                                                              |
| species__genus               | Genus               |                | Genus                                                                                    |
| plot__owner_orig_id          | External ID Number  | Owner Orig Id  | sigh. Pick a name and merge.                                                             |
| species__other_part_of_name  | Other Part of Name  |                | Other Part of Name                                                                       |
| plot__udf:Stewardship        | plot: Stewardship   | Stewardship    | planting site: Stewardship                                                               |
| udf:Stewardship              |                     | Stewardship    | tree: Stewardship                                                                        |
|                              |                     | Photos         | Don't merge                                                                              |
|                              | Tree Present        |                | Remove, hopefully                                                                        |
| species__fact_sheet_url      |                     |                | remove from export, or require opt-in                                                                      |
| species__fall_conspicuous    |                     |                | remove from export, or require opt-in                                                                      |
| species__flower_conspicuous  |                     |                | remove from export, or require opt-in                                                                      |
| species__flowering_period    |                     |                | remove from export, or require opt-in                                                                      |
| species__fruit_or_nut_period |                     |                | remove from export, or require opt-in                                                                      |
| species__has_wildlife_value  |                     |                | remove from export, or require opt-in                                                                      |
| species__id                  |                     |                | remove from export, or require opt-in                                                                      |
| species__is_native           |                     |                | remove from export, or require opt-in                                                                      |
| species__max_diameter        |                     |                | remove from export, or require opt-in                                                                      |
| species__max_height          |                     |                | remove from export, or require opt-in                                                                      |
| species__otm_code            |                     |                | remove from export, or require opt-in                                                                      |
| species__palatable_human     |                     |                | remove from export, or require opt-in                                                                      |
| species__plant_guide_url     |                     |                | remove from export, or require opt-in                                                                      |
| species__species             |                     |                | remove from export, or require opt-in                                                                      |

**Comment by maurizi** [comment]
I believe `OpenTreeMap Plot ID` in the importer is a `Plot` id, not a `Tree` id, and that we should keep it (and come up with a consistent name).

**Comment by steventlamb** [comment]
the latest iteration on the table:

| (1)tree export               | (2)import template  | (3)mgmt        | plan                                                                                     |
| -----------------------------|---------------------|----------------|------------------------------------------------------------------------------------------|
|                              | Tree Present        |                | merge 1+2 to 'Tree Present', add to base export                                                                        |
| date_removed                 |                     | Date Removed   | merge all to 'Date Removed', add to import template                                                     |
| diameter                     | Diameter            | Diameter       | merged                                                           |
| date_planted                 | Date Planted        | Date Planted   | merge to 'Date Planted'                                                                             |
| plot__geom__x                | Point X             | Geom           | merge 1+2 to 'Point X'                                                           |
| plot__geom__y                | Point Y             | Geom           | merge 1+2 to 'Point Y'                                                           |
| height                       | Tree Height         | Height         | merge 1+2 to Tree Height                                                                              |
| plot__width                  | Plot Width          | Width          | merge 1+2 to 'Planting Site Width'                                                                      |
| plot__length                 | Plot Length         | Length         | merge 1+2 to 'Planting Site Length'                                                                     |
| species__cultivar            | Cultivar            |                | merge 1+2 to 'Cultivar'                                                                                 |
| species__other_part_of_name  | Other Part of Name  |                | merge 1+2 to "Other Part of Name"                                                                       |
| plot__udf:Stewardship        | plot: Stewardship   | Stewardship    | merge 1+2 to "planting site: Stewardship"                                                               |
| udf:Stewardship              |                     | Stewardship    | merge 1+2 to "tree: Stewardship"                                                                        |
| species__common_name         | Common Name         |                | merge 1+2 to 'Common Name'                                                                              |
| species__genus               | Genus               |                | merge 1+2 to 'Genus'                                                                                    |
| plot__id                     |                     | Plot (also Id) | delete from base export, redudant with 'tree_plot/id'                                                                        |
| id                           |                     |                | delete from base export, confusing
| plot__readonly               |                     | Readonly       | delete from base export, leave unimplemented                                       |
| readonly                     |                     | Readonly       | delete from base export, leave unimplemented                                                                      |
| tree_plot                    | OpenTreeMap Plot ID | Id             | merge, render as 'id'                                                                |
| plot__owner_orig_id          | External ID Number  | Owner Orig Id  | merge all to 'Owner Orig Id', update docs. These drastically different names are a liability.|
| species__species             | Species             | Species        | merge to Species                                                                                  |
|                              |                     | Photos         |                                                                               |
| species__fact_sheet_url      |                     |                | remove from base export                                                                      |
| species__fall_conspicuous    |                     |                | remove from base export                                                                      |
| species__flower_conspicuous  |                     |                | remove from base export                                                                      |
| species__flowering_period    |                     |                | remove from base export                                                                      |
| species__fruit_or_nut_period |                     |                | remove from base export                                                                      |
| species__has_wildlife_value  |                     |                | remove from base export                                                                      |
| species__id                  |                     |                | remove from base export                                                                      |
| species__is_native           |                     |                | remove from base export                                                                      |
| species__max_diameter        |                     |                | remove from base export                                                                      |
| species__max_height          |                     |                | remove from base export                                                                      |
| species__otm_code            |                     |                | remove from base export                                                                      |
| species__palatable_human     |                     |                | remove from base export                                                                      |
| species__plant_guide_url     |                     |                | remove from base export                                                                      |
| species                      |                     |                | remove from export, ID not useful                                                                      |

**Comment by steventlamb** [comment]
Reopening and assigning to Rick, for easier reference
