### ISSUE TITLE
Wiki Installation instructions are out of date

### ISSUE THREAD

**Issue by maurizi** [OpenTreeMap/otm-core#2536]
Some issues:
 - They're written for Ubuntu 12.04, and we now use 14.04
 - They still reference our config file based way of getting database passwords, usernames, etc. to the various services

**Comment by nicoali** [comment]
Is there any news?
is there a millestone for that?

**Comment by RickMohr** [comment]
Draft of update is at
https://github.com/OpenTreeMap/otm-core/wiki/Updated-Installation-Guide-Draft

Once reviewed it will replace the current page.

**Comment by RickMohr** [comment]
The update is complete, and available at
https://github.com/OpenTreeMap/otm-core/wiki/Installation-Guide
