### ISSUE TITLE
Show a helpful message when a user tries to log in before activating their account

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#2550]
Rather than just showing the text "This account is inactive." we should explain that they need to click the link in their activation email. It would be ideal to also complete https://github.com/OpenTreeMap/otm-core/issues/1424 and provide a link to resend the activation email.

<img width="556" alt="screen shot 2016-04-01 at 9 43 22 am" src="https://cloud.githubusercontent.com/assets/17363/14213726/628cb0ba-f7ee-11e5-978b-7f274d4d9ba8.png">

**Comment by hadleystein1** [comment]
+1

**Comment by hadleystein1** [comment]
+1 Trees Forever. Related to https://github.com/OpenTreeMap/otm-addons/issues/720.

**Comment by jwalgran** [comment]
Now part of #3163
