### ISSUE TITLE
`cast_to_subtype` may fail if `self` is not a `MapFeaure`

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#2555]
In this rollbar issue https://rollbar.com/Azavea/OpenTreeMap/items/916/
we've instantiated a `MapFeature` whose `feature_type` is `"Plot"`, and used its `plot` attribute to get a `Plot` object. The `Plot` object's `feature_type` is also `"Plot"`, but it has no `plot` attribute.
That should not be possible. Django seems to be constructing the object incorrectly. 

So far we have only reproduced this in production (release 2.5.0) when a user is logged in.

**Comment by hectcastro** [comment]
Related details:

- All cases of this exception appear to have an authenticated user associated
- All cases are also related to either the Greenprint Maps or Carson City map instances
- Django and its dependencies were all at the same versions across 2.4.0 and 2.5.0
- A similar exception has occurred in testing, staging, and production
