### ISSUE TITLE
When zooming or resizing the map page quickly the z= url parameter cycles and the browser tab becomes unresponsive

### ISSUE THREAD

**Issue by jmorrison1847** [OpenTreeMap/otm-core#2558]
**Macbook Pro running OSX Yosemite 10.10.3 in Chrome version 49.0.2623.112**

I was only able to duplicate this behavior when turning satellite imagery on, but the basics are:
1. Aggressively zoom in/out and move the visible part of the screen
2. The screen freezes and the URL starts going quickly back-and-forth between two states (the part that denotes x/y)
3. Chrome becomes unresponsive.

A screen recording of the behavior can be viewed here:https://drive.google.com/a/azavea.com/file/d/0B_E16nocP-BpYUM3WE1tZTRnVTg/view?usp=sharing

**Comment by jwalgran** [comment]
I was able to reproduce this.

**Comment by hadleystein1** [comment]
+1

**Comment by jmorrison1847** [comment]
+1 from yegTreeMap

**Comment by jwalgran** [comment]
I am going to adjust the title of this issue because "crash" made me think of a different behavior than the one we are seeing.

**Comment by jmorrison1847** [comment]
+1 TreeMapLa; in this case, simply resizing the browser causes the behavior
