### ISSUE TITLE
Export cuts off leading zero in zip codes

### ISSUE THREAD

**Issue by hadleystein1** [OpenTreeMap/otm-core#2562]
Tree export cuts of leading zero in zip codes, requiring users to reformat from General > Special. Is there a way to convert this to a text column in .csv files to avoid this happening? 

![screen shot 2016-04-25 at 11 04 45 am](https://cloud.githubusercontent.com/assets/15219245/14789175/52a30c5a-0ad9-11e6-8368-2d4a4c65ecea.png)

**Comment by jwalgran** [comment]
I don't think we can prevent Excel from "helping" us by guessing that the zip code field is a number. CSV files are plain text and don't contain any metadata about the values stored in each column. I tried an experiment, wrapping the zip code with double quotes.

```csv
Point X,Point Y,Street Address,City,Postal Code,Planting Site Width,Planting Site Length,Planting Site Id,Owner Original Id,Tree Present,Genus,Species,Cultivar,Other Part Of Name,Common Name,Diameter,Tree Height,Canopy Height,Date Planted,Date Removed,Tree: Blocking signs,Tree: Branches damaged,Tree: Fall Color,Tree: In Bloom Now,Tree: Need to clear trash,Tree: Needs mulch,Tree: Needs to be weeded,Tree: Needs water,Tree: Remove dead tree,Tree: Stewardship,Tree: Tree Condition,Planting Site: Install tree pit,Planting Site: Stewardship,Planting Site: tree pit
-74.0574216843,40.7473219878,257 Hutton St,Jersey City,"07307",,,1656201,,True,,,,,,7.63943726841,25.0,,,,,,,,,,,,,,,,,
```

LibreOffice (which was behaving in the same way as the Excel example) unless I also used this option

<img width="192" alt="screen shot 2016-04-25 at 11 18 12 am" src="https://cloud.githubusercontent.com/assets/17363/14794167/736f3910-0ad7-11e6-804b-ff2af9d92a8f.png">

**Comment by hadleystein1** [comment]
@jwalgran Thanks for looking into the issue. It can be easily solved manually, but nice if there was a universal fix. Fortunately, it will only be an issue for states where zip codes start with 0 - so largely New England and Puerto Rico.

**Comment by jwalgran** [comment]
Closed because there is not a code change that will resolve the issue.
