### ISSUE TITLE
Export does not include Tree Number, only Planting Site ID

### ISSUE THREAD

**Issue by hadleystein1** [OpenTreeMap/otm-core#2563]
A professor using the JC Trees map wants Tree Number on the export along with Planting Site ID.

**Comment by maurizi** [comment]
This was a purposeful change - since Tree Number is not used in the import, and we wanted the exports to match the import template.

Long term, we would like to stop using Tree Number throughout the site, as Planting Site ID is a better identifier for the tree, since it is what is used in the URL for the tree detail page.

**Comment by maurizi** [comment]
@dboyer can we close this?

**Comment by dboyer** [comment]
I believe we decided to leave it open as blocked so that it is part of the larger discussion of planting site vs. tree ID number use throughout OTM.

**Comment by RickMohr** [comment]
I've moved this out of the priority backlog. Suggest we also remove the "High" label.

**Comment by dboyer** [comment]
Another OTM map owner expressed interest in seeing tree number in the export in addition to planting site number.

**Comment by RickMohr** [comment]
To do:
* add new field to export
* importer matches tree ID's and adds an error if tree not found
* update import schema version number

**Comment by RickMohr** [comment]
We have a policy of consistent field names -- a field's name should be the same in import/export headers and in the UI.

Currently that's not true for ID fields. We call them "Number" in the UI (e.g. "Tree Number", "Resource Number") but "ID" in import/export headers (e.g. "Planting Site ID").

I think we should standardize on either "ID" or "Number". Opinions? @dboyer, @hadleystein1, @jmorrison1847?
