### ISSUE TITLE
Cannot select tree dot after searching by geographic area

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-core#2569]
Tested on Mac in Chrome and Safari. Same behavior.

1. Search by a geographic area (neighborhood, zip code)
2. Geographic area is shaded on the map with tree dots visible within the polygon
3. Click on a tree dot that falls within the polygon
4. Nothing happens

This is on production as well as staging so was not introduced in the newest release.

**Comment by RickMohr** [comment]
Likely related to the changes in #2511 to support ESRI basemaps.

**Comment by RickMohr** [comment]
@jmorrison1847 writes:

Noted by LA Tree Map--when filtering down to a neighborhood (or presumably any set of boundary files), the trees within that neighborhood are correctly summarized but are not clickable.

Try Beverly Hills in LA: https://www.opentreemap.org/latreemap/map/?z=12/34.0825/-118.3997&q=%7B%22mapFeature.geom%22%3A%7B%22IN_BOUNDARY%22%3A%2230798%22%7D%7D

Or China Town North in Philly: https://www.opentreemap.org/phillytreemap/map/?z=15/39.9588/-75.1507&q=%7B%22mapFeature.geom%22%3A%7B%22IN_BOUNDARY%22%3A%2231411%22%7D%7D

**Comment by jmorrison1847** [comment]
Oop, did not see this had already been noted, thanks @RickMohr!
