### ISSUE TITLE
Add support for “custom_layers” in the instance configuration

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#2577]
[{“name”: “Tree Canopy, “type”: “tile”, “url”: “http://tiles.com/foo/{z}/{x}/{y}.png”
"show_by_default": true}]

Update the map layer selector to read these from the configuration and show them

**Comment by RickMohr** [comment]
So `instance.config` would include for example:
```json
{
    "layers": [
        {
            "name": "Tree Canopy",
            "type": "tile",
            "url": "http://tiles.com/foo/{z}/{x}/{y}.png",
            "showByDefault": true
        }
    ]
}
```

**Comment by RickMohr** [comment]
We decided further:
* We'll also show these layers on the detail page mini-map, using the same parameters
* We'll allow specifying max zoom
