### ISSUE TITLE
After searching by address show a dot on the map

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#2588]
- The dot should be clearly distinguishable from a tree or stormwater feature.
- The dot should not obscure a map feature and block click events.
- The dot should be removed when searching for a different location

Related to [Address search zooms in but does not highlight tree](https://github.com/OpenTreeMap/otm-core/issues/2564) but different.

**Comment by jmorrison1847** [comment]
+1 Greening of Detroit

**Comment by jmorrison1847** [comment]
+1 Wingfield Springs
