### ISSUE TITLE
Show canopy percentage at point

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#2590]
NOTE: Reuse the click handling for green infrastructure

- Add function to retrieve boundary names, categories, and canopy percent at a specified lat/lng.

- Include boundary names, categories, and canopy percentage in the tree detail popup.

- AJAX endpoint returns boundary names, categories, and canopy percentages at a specified lat/lng.

- When clicking the map away from a tree point, show the boundary names, categories, and canopy percentage

**Comment by RickMohr** [comment]
Once this is implemented we'll start seeing canopy info on any treemap which happens to intersect a boundary with canopy data. For example, if somebody made a Pittsburgh tree map they would see the canopy percentages but not the canopy layer. Is that OK? 

If not, we'll want a configuration entry to explicitly enable showing canopy data.

**Comment by jwalgran** [comment]
https://github.com/OpenTreeMap/otm-core/pull/2593 added a `canopy_enabled` field to `Instance` so we can control who sees the canopy features.
