### ISSUE TITLE
Can't add Enhanced Instance in Django admin

### ISSUE THREAD

**Issue by kdeloach** [OpenTreeMap/otm-core#2592]
I noticed 2 problems in the Django admin page for Enhanced instances.

The Tier dropdown doesn't contain human-friendly names.

![screenshot 2016-05-20 at 18 38 05](https://cloud.githubusercontent.com/assets/43062/15443939/1b5a4dd6-1eba-11e6-83ef-7cdebbe8204c.png)

When you click Save there is an exception.

> UserTrackingException at /admin/cloud_management/enhancedinstance/add/
All changes to EnhancedInstance objects must be saved via "save_with_user"

**Comment by maurizi** [comment]
We don't really support the Django admin site right now for any model.
