### ISSUE TITLE
Tree identified as part of polygonal map feature when green infrastructure not turned on

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-core#2599]
On staging, see /testmap0523/features/1339114/

I added this tree via the normal add process. It indicates the tree is part of a polygonal map feature, but when I click to go to that map feature, I get an error page.

The Google Street View indicates the tree is an area associated with the "Independence National Historical Park" area. Perhaps this is related to search boundaries?

**Comment by dboyer** [comment]
Replicated at /testmap0523/features/1330493/ but not at /testmap0523/features/1339113/

**Comment by RickMohr** [comment]
A different map has a "Fairy Garden" at the same location -- see staging /testmap0316/map/?z=17/39.94740/-75.15163
