### ISSUE TITLE
Planting Site Deletion Behavior ≠ Permissions

### ISSUE THREAD

**Issue by jmorrison1847** [OpenTreeMap/otm-core#2621]
Reported by Baton Rouge Green and LA Tree Map separately:

Both emailed to say that they were having trouble deleting planting sites. They could delete trees, but not their respective planting sites. After some investigation, making _every_ field "Full Write Access" appears to clear up the problem. To quote from MyTreeBR: 

> We had one or two fields under the "Planting Site > Admin column" switched to 'invisible'.  When I switched ALL fields under in this column to 'Full Write' it allowed me (an administrator) to finally delete the planting site.

The trouble is that fields like "Stewardship" are preventing deletion of planting sites if set to invisible (haven't tested "read only" yet) even though they should have nothing to do with deletion permissions. But if a map wants users to be able to delete misplaced planting sites, they have to give them Full Write Access to every field (not ideal, especially if you are experimenting with new fields or want certain fields to remain invisible).

**Comment by RickMohr** [comment]
Another customer vote for a simple "delete" permission.

**Comment by jwalgran** [comment]
Implementing [Users should be able to delete trees they entered (#1003)](https://github.com/OpenTreeMap/otm-core/issues/1003) would resolve this issue.

**Comment by maurizi** [comment]
This was fixed by https://github.com/OpenTreeMap/otm-core/issues/1003!
