### ISSUE TITLE
Eco-benefit coefficients clear out after bulk uploading data

### ISSUE THREAD

**Issue by hadleystein1** [OpenTreeMap/otm-core#2630]
Uploaded 10,000+ trees to a trial map and when the uploaded completed it appears that the coefficients used to calculate ecosystem benefits were cleared out of the system. @jmorrison1847 experienced the same issue during an upload last week.

Financial benefit values not populating after bulk upload:
![screen shot 2016-06-20 at 11 43 05 am](https://cloud.githubusercontent.com/assets/15219245/16200671/3c9606f4-36dc-11e6-9220-d1519cd2ea5e.png)

Ecosystem page appears to have no information:
![screen shot 2016-06-20 at 11 35 52 am](https://cloud.githubusercontent.com/assets/15219245/16200635/20acf48e-36dc-11e6-8a25-308091a1d3fa.png)

Copied over information from other map, but benefits still do not seem to be calculating.
![screen shot 2016-06-20 at 11 36 31 am](https://cloud.githubusercontent.com/assets/15219245/16200685/4b389410-36dc-11e6-9b40-ae1f893ea7d2.png)

**Comment by RickMohr** [comment]
@hadleystein1 this was entered previously as https://github.com/OpenTreeMap/otm-addons/issues/1006, but we need to fix it. I'm adding it to our "immediate issues" for this sprint.

**Comment by RickMohr** [comment]
Reopening, becuase OpenTreeMap/otm-addons#1006 doesn't include the loss of coefficients after upload.

**Comment by RickMohr** [comment]
Moved to https://github.com/OpenTreeMap/otm-addons/issues/1192
