### ISSUE TITLE
A popup is not displayed when clicking a stormwater feature

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#2652]
1. Create an instance with the green infrastructure module
1. Activate "Rain Gardens"
1. Add a tree 
1. Add a rain garden
1. On the map page, click the tree, then click the rain garden

Expected: A popup is shown over every clicked feature
Actual: A popup is shown over a clicked tree, but not a clicked rain garden

In the network tab of the web inspector you can see a successful request for the rain garden popup content, the content is just not being displayed.

**Comment by RickMohr** [comment]
I wonder if it's collateral damage from our recent work updating the popups with canopy info.
