### ISSUE TITLE
Search filters do not change if a geocoded address is active

### ISSUE THREAD

**Issue by kdeloach** [OpenTreeMap/otm-core#2660]
Steps:

1. Select a geocoded address from the locations autocomplete dropdown

2. Toggle between `Show trees` and `Show empty planting sites` under `Display` in the advanced search filters

Expect:
The map and the URL in the address bar should update to reflect the selected filters.

Actual:
Nothing happens.

**Comment by kdeloach** [comment]
Verified on staging.

**Comment by jwalgran** [comment]
Verified on production as well.
