### ISSUE TITLE
After editing a rain garden / bioswale polygon on the detail page, the area field does not update

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#2667]
1. Add a rain garden and go to its detail page
2. Edit the rain garden's polygon and save
3. The area field does not update
4. Refresh the page and the area is updated

**Comment by RickMohr** [comment]
On a successful save, re-fetch and replace inner content of page.
Also replace special-purpose code that was introduced to solve similar problems without a refresh. (Possibly review past issues to locate such code.)

**Comment by jwalgran** [comment]
I was testing https://github.com/OpenTreeMap/otm-core/pull/2710/files and saw that the eco benefits were not updating after editing the drainage area. Will the solution you are working on handle eco benefits?

**Comment by RickMohr** [comment]
Yes!
