### ISSUE TITLE
Staging: Bioswales displayed as dots rather than polygons

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#2672]
Problem appears on staging but not on production or my dev machine:

[Staging](https://staging.opentreemap.org/gowanustrees/map/?z=18/40.67434/-73.99128):
![image](https://cloud.githubusercontent.com/assets/2162993/16886913/c9a4699c-4a8b-11e6-86b0-e0da8a725443.png)

[Production](https://www.opentreemap.org/gowanustrees/map/?z=18/40.67434/-73.99128) and my dev machine:
![image](https://cloud.githubusercontent.com/assets/2162993/16886941/e92d4220-4a8b-11e6-8921-641b6c9f3c24.png)

**Comment by RickMohr** [comment]
Related -- clicking on a blue dot causes e.g.
https://rollbar.com/Azavea/OpenTreeMap/items/1328/occurrences/14602218056/

**Comment by RickMohr** [comment]
@jwalgran, I'd call this a release blocker

**Comment by jwalgran** [comment]
I agree. I am mobile and can't change milestones. Please add this to 2.10.

**Comment by jwalgran** [comment]
I created a new instance, added trees to roughly match the extent of the gowanus map, and then added a bioswale. It is rendering correctly as a polygon.

https://staging.opentreemap.org/jw-2016-07-18-2

<img width="859" alt="screen shot 2016-07-18 at 11 09 03 am" src="https://cloud.githubusercontent.com/assets/17363/16925234/1257a746-4cd8-11e6-821a-957accbe1e35.png">

**Comment by jwalgran** [comment]
This query for map features that don't have a related row in `stormwater_polygonalmapfeature` returns results on the staging server, but not in production or my dev VM.

```sql
SELECT m.id, url_name
FROM treemap_mapfeature m
JOIN treemap_instance i ON m.instance_id = i.id
WHERE feature_type in ('Bioswale', 'RainGarden')
AND m.id NOT IN (SELECT mapfeature_ptr_id FROM stormwater_polygonalmapfeature);
```

At some point, the `stormwater_polygonalmapfeature` rows were deleted, but the parent `treemap_mapfeature` rows were not.

**Comment by jwalgran** [comment]
Closing because this appears to be an isolated incident.
