### ISSUE TITLE
Add support for displaying dates before 1900

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#2687]
Resolving this issue may resolve the issue https://github.com/OpenTreeMap/otm-core/issues/2686 without additional work.

There are "heritage trees" that were planted before 1900. We need an alternative to `strftime` because

> `strftime() methods require year >= 1900`

**Comment by dboyer** [comment]
This appears to be fixed.

**Comment by jwalgran** [comment]
Yes. I am able to see old planting dates on PTM.
<img width="863" alt="screen shot 2017-08-22 at 8 35 16 am" src="https://user-images.githubusercontent.com/17363/29573905-000e5ab2-8715-11e7-8774-66a08010fbb1.png">
