### ISSUE TITLE
Add drainage area square footage as an optional field on rain gardens and bioswales

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#2688]
After further discussions with our advisors, we have determined that eco benefit calculations for these resources will need to take into account the square footage of area that drains to the rain garden/bioswale in addition to the area of the rain garden/bioswale itself.

Use rain barrels as a reference, since they already collect and display a capacity field.

**Comment by dboyer** [comment]
Remember to show and collect in the map's units, but convert and store in a specific database units.

**Comment by RickMohr** [comment]
Users could be confused whether the drainage area should include or omit the area of the rain garden, and we don't currently have a mechanism for including help text.

**Comment by dboyer** [comment]
Could we repurpose how we use help text by the diameter?

**Comment by RobinIsTheBird** [comment]
Both tree species and diameter have help text that are hyperlinks off site, and the latter is a video so it has a video icon.

A hyperlink strikes me as overkill for this clarification, which could be simply stated in one sentence  (@dboyer, can you provide one?)

I could see either including the help text right below the input, like species and diameter, or adding an info icon (i in a filled circle) to the label, with a tooltip on hover. There may be many other solutions, but those are what leap to my mind.

What would you like to see?

**Comment by dboyer** [comment]
Just saw this! A line of text by the field is fine with me. Text is:

Please enter an estimate of the area that drains to the feature. Do not include the area of the feature itself.

If possible, I'd like "feature" to use whatever term the map owner has entered for "resource."

**Comment by RickMohr** [comment]
Since the field will be shown on the detail page for a rain garden or bioswale we can use the actual resource name, e.g.

Please enter an estimate of the area that drains to the bioswale. Do not include the area of the bioswale itself.
