### ISSUE TITLE
instance config does not play well with test infrastructure

### ISSUE THREAD

**Issue by RobinIsTheBird** [OpenTreeMap/otm-core#2703]
An otm-addons test best demonstrates the problem, but I believe the underlying problem is in otm-core.

The demonstration test case is otm-addons.cloud_management.tests.test_management.UnitsTest.

The following code excerpt succeeds on my localhost but fails on Jenkins, even if I run all 11 1/2 minutes worth of tests locally.

```
        instance = make_instance(url_name='basic')
        owner = make_admin_user(instance)
        ei = EnhancedInstance(instance=instance, owner=owner)
        ei.feature_enabled_green_infrastructure = False
        ei.save_with_user(owner)
        specs = units(None, instance)

        self.assertEqual(len(specs['value_specs']), 3)
```

On Jenkins, it fails, saying 4 != 3. Instrumentation reveals that on Jenkins, the config includes Bioswale.

If you add the following line before the call to `units()`, it then passes on Jenkins.

`        instance.remove_map_feature_types(keep=['Plot'])
`

A new instance from make_instance ought not to have any stormwater map feature types in its config.

**Comment by RickMohr** [comment]
A likely suspect is mistakenly updating the default value of an instance config property. A quick thing to check would be changing this line of code:

https://github.com/OpenTreeMap/otm-core/blob/5c139aea0a34e3420239e4ba428924fb448000e3/opentreemap/treemap/instance.py#L243

to something like:

```
return self.config.get(prop, deepcopy(default))
```

**Comment by maurizi** [comment]
Another possible solution is to bring in this Python module and run `freeze` on all of our default config dictionaries  - which would fix the issue for things used as `_make_config_property` defaults and prevent any problems when/if they are used outside of `_make_config_property`

**Comment by RobinIsTheBird** [comment]
I introduced the bug, and the bug is here: https://github.com/OpenTreeMap/otm-core/blob/develop/opentreemap/stormwater/tests.py#L22

That said, I think the list ought to be kept as a tuple to prevent noob errors like that, which are so costly to track down or work around. I'll make both changes tomorrow.

**Comment by RickMohr** [comment]
My `deepcopy` proposal would prevent code like this from affecting the default value.

**Comment by RobinIsTheBird** [comment]
Yep, on closer inspection, you are correct Rick. I'm using deepcopy.

I've also renamed map_feature_types to _map_feature_types and added a read-only map_feature_types property, as well as docstrings explaining how to use it.

**Comment by RobinIsTheBird** [comment]
Turns out I didn't introduce the bug. Steve Lamb shows up in git blame.

But I did make the same mistake initially, and only corrected myself later on.
