### ISSUE TITLE
Terminology changes on green infrastructure management page

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-core#2704]
Text for help icon:

The runoff coefficient represents how the slope and material of the drainage area impact the amount of runoff that reaches the rain garden. We recommend 0.85 as an average number, but this field may be edited.

**Comment by RobinIsTheBird** [comment]
Below is information from emails sent by @dboyer that I assume is part of this ticket.

Annual rainfall x (area of polygon + (square footage of area that drains to the rain garden x constant number ))

Displaying it as 0.85 on the management page would be preferable as that's how it is displayed as part of something called the "Rational Equation Method" - http://www.lmnoeng.com/Hydrology/rational.php - which is often used for this type of GSI calculation.

Regarding help text, A line of text by the field is fine with me. Text is:

Please enter an estimate of the area that drains to the feature. Do not include the area of the feature itself.

(replace "feature" with the appropriate terminology for rain garden or bioswale)

**Comment by RobinIsTheBird** [comment]
@dboyer Can you please supply new help text for the tooltip on the runoff coefficient (currently called "ecobenefits constant") on the green infrastructure page? It currently says, "Enter a weighted number 0-100". At a minimum, we need to change it to the range 0 to 1. The word "weighted" doesn't make much sense in this context either.

**Comment by RobinIsTheBird** [comment]
@dboyer The add a resource step for entering the drainage presently reads, "What is the area of adjacent drainage?"

1) Does it need more explanation?
2) If so, where does the additional explanation belong? I suggest an information icon ( "i" in a black circle) to the right of the question, with the explanation in a tooltip.

**Comment by RobinIsTheBird** [comment]
Here's a screenshot of the drainage area step as it is today...

![screenshot from 2016-08-16 15 31 06](https://cloud.githubusercontent.com/assets/1473263/17713158/6c8e72e8-63c7-11e6-99ca-e6be732429bf.png)

**Comment by dboyer** [comment]
Tooltip text on the management page can be:

The runoff coefficient represents how the slope and material of the drainage area impact the amount of runoff that reaches the rain garden. We recommend 0.85 as an average number, but this field may be edited to include a number between 0 and 1.

For the drainage area, let's word the question as: "What is the estimated area that drains into the resource?"

Some additional information would be helpful. Let's use the below wording. I'm fine with an info icon and tooltip, but I can't remember if we use those elsewhere on the public side of the site. We do use blue information boxes such as what appears in Step 1 of the add a tree process. Perhaps check with Scott to get some design guidance.

"Please enter an estimate of the area that drains to the resource. Do not include the area of the resource itself." 

Note: Resource should be replaced with whatever word the map owner set for that resource (rain garden, bioswale, etc).

**Comment by RobinIsTheBird** [comment]
@dboyer , here is Scott's mock. He's offering some different wording from your proposal...

![proposal_otm-core2704](https://cloud.githubusercontent.com/assets/1473263/17742275/590039f4-646d-11e6-806b-420e254f7128.png)

**Comment by dboyer** [comment]
That looks fine with one change. Can you change the second sentence of the help text to read "Do not include the area of the resource itself." 

I want to repeat the word area rather than size since we use area for the question.

**Comment by RobinIsTheBird** [comment]
@dboyer The recommended help text for the runoff coefficient circle-i on the green infrastructure page doesn't fit in a bootstrap tooltip.

Scott recommends:  "Fraction of adjacent drainage area runoff that reaches the rain garden. Between 0 and 1."

That's what I'll use until further notice.

**Comment by dboyer** [comment]
That's fine for now. Long term, we should probably add an option for help text near fields on the management page. But that's a task for another time.
