### ISSUE TITLE
Newly-added bioswale doesn't contribute to total ecobenefits

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#2707]
If you add a bioswale and select it you will see its ecobenefits but they do not contribute to the total ecobenefits. If you modify one of its fields then it will contribute to the total.

**Comment by RobinIsTheBird** [comment]
I've also seen removed resources continuing to be reflected in the total ecobenefits. Clearly a caching issue.

**Comment by RobinIsTheBird** [comment]
Puzzling. The code looks like it does the right thing with the cache. Must be something else.

**Comment by RobinIsTheBird** [comment]
I know I've seen this sort of misbehavior in the past, but now I can't reproduce it.

**Comment by RickMohr** [comment]
This happened during RRP on staging. Closing because @RobinIsTheBird can't reproduce it and says the code looks right.
