### ISSUE TITLE
Upgrade to Django 1.11

### ISSUE THREAD

**Issue by RobinIsTheBird** [OpenTreeMap/otm-core#2724]
There may be many other compelling reasons to upgrade, but the one that feels compelling to me is the `asvar` parameter to [`blocktrans`](https://docs.djangoproject.com/en/1.10/topics/i18n/translation/#std:templatetag-blocktrans).

We will also need to upgrade any django-* packages if necessary for 1.11 compatibility.

**Comment by jwalgran** [comment]
We will need to consider the roadmap when deciding on Django upgrades. 1.8 is an LTS release which Django has [committed to patching through at least April 1 2018](https://www.djangoproject.com/weblog/2015/apr/01/release-18-final/). 

```
Release Series   Release Date   End of mainstream support   End of extended support
-----------------------------------------------------------------------------------
1.9              December 2015  August 2016                 April 2017
1.10             August 2016    April 2017                  December 2017
1.11 LTS         April 2017     December 2017               Until at least April 2020
2.0              December 2017  August 2018                 April 2019
```
https://www.djangoproject.com/weblog/2015/jun/25/roadmap/

We are using at lease one deprecated Django feature that will require a us to refactor when moving off of 1.8 https://github.com/OpenTreeMap/otm-core/issues/1968

**Comment by jwalgran** [comment]
I updated the title because we have decided to upgrade to the next LTS, 1.11.

**Comment by jwalgran** [comment]
Blocked by #3133

**Comment by maurizi** [comment]
Fixed in https://github.com/OpenTreeMap/otm-core/pull/3164
