### ISSUE TITLE
Embed query string

### ISSUE THREAD

**Issue by RobinIsTheBird** [OpenTreeMap/otm-core#2736]
1. Handle an embed query string parameter in the urls for the map page, the detail panel, and the popup.
2. On the map page, forward the embed query string to the detail and popup urls.
3. Strip header and footer from the map page for embed.
4. Modify the following links to redirect to opentreemap.org for the same treemap, in a separate tab or window:
   - popup View All Details
   - popup Edit Details
   - detail Full Details
   - detail Quick Edit
   - man map Export link
5. Add the html snippet for the iframe in a template, parameterized by size in the context.
6. Demonstrate the appearance of the iframe on a webpage for a demo website.

**Comment by dboyer** [comment]
Just to confirm - the "detail panel" means the right sidebar, correct? Not the detail page? I see from 4 that the view all details and full details should open in a new page (which is correct) so wanted to confirm what the detail panel meant.

**Comment by RobinIsTheBird** [comment]
The links in the sidebar detail panel need to be modified to pop up a new tab or window. The url in the new tab or window would refer to the detail page, in view or edit mode. If authentication is required, the new tab|window will display a prompt to login.

Sorry for the confusion.

**Comment by dboyer** [comment]
Thanks for clarifying. Sounds great!

**Comment by RobinIsTheBird** [comment]
@dboyer , @lederer , for now, I've got embed mode taking away the Quick Edit button in the sidebar details panel when a tree/plot is selected.

This is easier than changing the name to just "Edit" and opening a new tab or window.

Is this acceptable for now?
