### ISSUE TITLE
Searches with single result should select that result

### ISSUE THREAD

**Issue by RobinIsTheBird** [OpenTreeMap/otm-core#2745]
Any search with a single result — over any fields — selects that result.

**Comment by jwalgran** [comment]
Right now, the results of a filter are returned as rendered HTML (from `/{instance}/benefit/search/`). Deciding how to add the additional information we need to show a selected feature be a design challenge. One possible implementation would be to conditionally add a data attribute to an element in the returned markup, something like `data-matched-feature-id`, and then have the handler that patches the markup into the DOM also trigger the selection process.
