### ISSUE TITLE
Design viewport adjustment on search

### ISSUE THREAD

**Issue by RobinIsTheBird** [OpenTreeMap/otm-core#2746]
Every search should have a way to adjust the viewport to frame the results.

**Comment by jwalgran** [comment]
We have an old issue that proposes following the lead of desktop GIS tools and only zooming the map to fit the results when the user explicitly requests it: https://github.com/OpenTreeMap/otm-core/issues/753. We need to decide how exactly to implement this. Some options:

* Zoom automatically
* Zoom when requested
* Zoom when requested unless an "auto zoom" checkbox is checked (Checked by default?).

**Comment by RobinIsTheBird** [comment]
Duplicates #753. Moving design discussion there.
