### ISSUE TITLE
Unstyled detail page after editing and favoriting details

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-core#2749]
Tested in Chrome on staging:

1. Visit tree detail page and edit field
2. Click Save - page saves correctly
3. Click the star to favorite the tree
4. Page reloads with no styling (see attachment)

I reproduced the steps when clicking the star again to remove it as a favorite. Replicated for other detail pages.

![otm_unstyled_detail_page](https://cloud.githubusercontent.com/assets/516764/18132273/272d149a-6f64-11e6-8358-aaea1156c954.png)

**Comment by dboyer** [comment]
@RickMohr Perhaps related to the page refreshing work?

**Comment by RickMohr** [comment]
Yes, most likely. Will jump on it tomorrow morning.
