### ISSUE TITLE
Date picker does not display when first clicking in date field on stewardship entry

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-core#2750]
Testing on staging in Chrome:

1. Visit tree detail page and click edit
2. Select stewardship action
3. Date field says "today." Click in date field.
4. No date picker appears
5. Add stewardship entry with date of "today" which system converts to 8/31/2016
6. Save page
7. Click edit again, same issue with date picker
8. Manually type in date for stewardship entry
9. Date saves correctly

The date picker should appear when the date field is selected.

**Comment by dboyer** [comment]
The date picker is periodically not appearing when I edit the date planted or removed fields but I can't reliably reproduce that. It seems to not appear the first time I click the field, but it will appear if I reload the page.

**Comment by dboyer** [comment]
I can't reproduce this in Firefox or IE so may be a Chrome specific issue.

**Comment by jwalgran** [comment]
These are the results of my testing:

In Chrome on OS X, when the detail page has been loaded for the first time, I am always seeing date pickers appear when focusing any date field.

If I save, then click edit again, any date field that does not already have a valid date does not show a date picker when the field is focused, including the stewardship date field, which contains the word "Today."

If I reload the detail page and edit->cancel->edit, all the date fields show date pickers when focused.

Here are the steps I went through:

1. Add a plot with a tree. Navigate to the detail page.
1. Click edit.
  1. Verify date pickers
    1. Date picker appears when focusing Date Removed
    1. Date picker appears when focusing Date Planted
    1. Date picker appears when focusing the tree stewardship date field with the text "Today" 
  1. Set the Date Planted to a valid date.
  1. Click "+" to add a tree stewardship item.
  1. Click save.
1. **Refresh** the detail page
1. Click edit, verify the date pickers
  1. Date picker appears when focusing the empty Date Removed
  1. Date picker appears when focusing Date Planted
  1. Date picker appears when focusing the tree stewardship date field with the text "Today" 
1. Click save
1. Click edit
  1. Date picker DOES NOT appear when focusing the empty Date Removed
  1. Date picker DOES appear when focusing Date Planted, which has a valid value
  1. Date picker DOES NOT appear when focusing the tree stewardship date field with the text "Today "

I was able to reproduce this same behavior in Firefox and Safari.
I could not reproduce this error in production.

Based on these finding my hypothesis is that event handlers are not being set up correctly after patch the updated page markup into the DOM after a successful save. I suspect either the upgraded datepicker (#2695), the updated save behavior (#2720), or a combination of both may have caused the regression.
