### ISSUE TITLE
ID field on comment management page does not click through to tree detail page

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-core#2752]
Gives the "no trees here" error instead.

**Comment by jwalgran** [comment]
I followed these steps on a staging instance and could not reproduce the issue:

1. Navigate to a tree detail page.
1. Add a comment.
1. Navigate to `/{instance}/management/comment-moderation/.
1. Click the ID next to the newly added comment. 

Are these steps different than the ones you took? 
Are you able to reproduce the issue?

**Comment by dboyer** [comment]
I can't reproduce it today so closing this.
