### ISSUE TITLE
exporter/tests.py fails some versions of flake8

### ISSUE THREAD

**Issue by RobinIsTheBird** [OpenTreeMap/otm-core#2761]
On travis:
```
4.69s$ flake8 --exclude migrations,opentreemap/settings/local_settings.py,*.pyc opentreemap
opentreemap/exporter/tests.py:313:1: F999 dictionary key u'last_edit_model' repeated with different values
opentreemap/exporter/tests.py:314:1: F999 dictionary key u'last_edit_model_id' repeated with different values
opentreemap/exporter/tests.py:315:1: F999 dictionary key u'last_edit_instance_id' repeated with different values
opentreemap/exporter/tests.py:316:1: F999 dictionary key u'last_edit_user_id' repeated with different values
opentreemap/exporter/tests.py:319:1: F999 dictionary key u'last_edit_model' repeated with different values
opentreemap/exporter/tests.py:320:1: F999 dictionary key u'last_edit_model_id' repeated with different values
opentreemap/exporter/tests.py:321:1: F999 dictionary key u'last_edit_instance_id' repeated with different values
opentreemap/exporter/tests.py:322:1: F999 dictionary key u'last_edit_user_id' repeated with different values
```

The complaints are correct. Here's the code at fault:
```
        self.assertUserJSON(user2data,
                            {'last_edit_model': 'Plot',
                             'last_edit_model_id': str(self.plot.pk),
                             'last_edit_instance_id': str(self.instance.pk),
                             'last_edit_user_id': str(self.user1.pk),
                             'email': 'genly@example.com',
                             'email_hash': self.user2.email_hash,
                             'last_edit_model': 'Tree',
                             'last_edit_model_id': str(self.tree.pk),
                             'last_edit_instance_id': str(self.instance.pk),
                             'last_edit_user_id': str(self.user2.pk)})
```

It was last edited in 2014 by Steve Lamb. I don't know how anybody ever thought this test actually worked.

Commenting out the test until this bug gets scheduled.

**Comment by RobinIsTheBird** [comment]
To clarify, having a test _pass_ is not the same thing as having the test _work_.  A test _works_ if it actually tests what it sets out to test, whether it passes or fails. Given that the code at fault adds keys to a dict and immediately replaces them, we can't even really say what the intent of the test was. In that sense, it is not a working test even though it passes.

**Comment by jwalgran** [comment]
I pulled these lines from the build log of a Travis job that failed:

```
Collecting pyflakes>=0.6.1 (from flake8==2.0->-r requirements.txt (line 10))
  Downloading pyflakes-1.3.0-py2.py3-none-any.whl (222kB)
```
https://s3.amazonaws.com/archive.travis-ci.org/jobs/158170516/log.txt

It is probably worth checking to see if the loose specification on the transitive `pyflakes` dependency is causing the discrepancies between environments.

**Comment by RobinIsTheBird** [comment]
@jwalgran , would checking and, if necessary, fixing the loose specification be part of this issue, or should we create another one?

**Comment by jwalgran** [comment]
I think it makes sense for it to be part of this issue.

**Comment by jwalgran** [comment]
The specific lint that triggered this issue was removed in https://github.com/OpenTreeMap/otm-core/pull/2762 so it will not be reproducible.
