### ISSUE TITLE
Save tree details with invalid species does not produce an error message

### ISSUE THREAD

**Issue by RobinIsTheBird** [OpenTreeMap/otm-core#2764]
Click on a tree that has a valid species, and Edit Details.

Change the species to "no such thing" and click Save.

It goes back to display mode, showing the original species name.

**Comment by maurizi** [comment]
I can't replicate this. Instead of showing the original species, it _clears_ the species field, which seems like OK behaviour.

@dboyer Should I close this?

**Comment by dboyer** [comment]
I can replicate it in Chrome by:

1. Selecting a tree with an existing species
2. Clicking Edit on the detail page
3. In the species field, typing nonsense text but then not clicking anywhere else on the page
4. Clicking Save
5. It saves with the original species

If I click off the field, it clears the species field.
