### ISSUE TITLE
Negative diameter does not produce an error message

### ISSUE THREAD

**Issue by RobinIsTheBird** [OpenTreeMap/otm-core#2767]
Click on a tree that has a valid diameter, and Edit Details.

Change the diameter to a negative number and Save. It refreshes into display mode with the original diameter.

It ought to produce an error message and remain in edit mode.

**Comment by maurizi** [comment]
I just attempted to replicate this, and encountered a different bug.

I entered `-2` as the diameter, and it was saved as `2` instead.

**Comment by dboyer** [comment]
I replicated this bug where the negative diameter saves as the positive version of the number.
