### ISSUE TITLE
Show external link on map feature detail page

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#2785]
<img width="1195" alt="screen shot 2016-09-16 at 12 18 30 pm" src="https://cloud.githubusercontent.com/assets/17363/18598470/b86fb408-7c07-11e6-93b8-56a850a3e821.png">

A possible schema for how a tokenized external link will be stored in the instance config

``` python
{
  'external_link': {
    'text': 'Somthing',
    'url': 'http://someapp.com/{tree.id}'
  }
}
```

Show the link on the detail page only if:
- The instance config contains an `external_link` key.
- The value of the `external_link` key is an object with non-empty `text` and `url` keys.
- If the `url` contains a token, that token can be replaced with a non-empty value from the current feature.

**Comment by jwalgran** [comment]
Blocked while we determine when to show the link based on role membership

**Comment by dboyer** [comment]
Tampa confirmed they would prefer an approach that supports setting the ability to view the link based on user roles. Their timeframe does not require us to implement a different solution and they can wait for the roles based permissions.
