### ISSUE TITLE
Update to Leaflet 1.0

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#2812]
We are on a patched version of Leaflet 0.6.4 -- very old.
1.0 has been extremely well-tested, and has features we want (like more control over stacking order of layers). Today I tried to use a feature but failed since it was introduced in 0.7.0
We've been waiting for 2 years. It's time.

Code comments relevant to Leaflet upgrade
* [x] https://github.com/OpenTreeMap/otm-addons/blob/develop/modeling/js/src/lib/scenarioUi.js#L349
* [x] https://github.com/OpenTreeMap/otm-core/blob/develop/opentreemap/treemap/js/src/lib/boundarySelect.js#L22
* [x] https://github.com/OpenTreeMap/otm-core/blob/develop/opentreemap/treemap/js/src/lib/layers.js#L98
* [x] https://github.com/OpenTreeMap/otm-core/blob/develop/opentreemap/treemap/js/src/lib/MapManager.js#L283
* [x] https://github.com/OpenTreeMap/otm-core/blob/develop/opentreemap/treemap/js/src/lib/MapManager.js#L358

### Plugins
npm
* [x] esri-leaflet
* [x] leaflet-pip

vendor
* [x] leaflet.draw.js

shim
* [x] leaflet.bing.js
* [x] leaflet-editable-polyline.js
* [x] Google maps tiles
* [x] leaflet.utfgrid.js

**Comment by jwalgran** [comment]
We may want to merge [When upgrading from Leaflet 0.6.4, resolve source code patch](https://github.com/OpenTreeMap/otm-core/issues/776) into this issue.

**Comment by RickMohr** [comment]
I started working on this with R&D time -- see https://github.com/RickMohr/otm-core/commits/leaflet-1.0
