### ISSUE TITLE
Map page requests tiles from the inistial zoom level and the zoom level specified by the `z=` query parameter

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#2814]
This appears to be a regression. It was addressed several years ago in https://github.com/OpenTreeMap/otm-core/pull/1137
- Open the Network tab of Developer Tools
- Browse https://www.opentreemap.org/latreemap/map/
  - Tiles requests with zoom level `/8/` in the URL appear in Developer Tools
- Clear the Developer Tools Network tab.
- Browse https://www.opentreemap.org/latreemap/map/?z=17/34.14443/-117.77685
  - Tile requests for both zoom level `/8/` and zoom level `/17/` appear in Developer Tools

**Comment by RickMohr** [comment]
I think this may not be a regression -- #1137 addressed some but not all issues of tile loading / zoom.

I'd like to see if it's still a problem with Leaflet 1.0.

**Comment by RobinIsTheBird** [comment]
I can't reproduce it using leaflet 1.0.3.
