### ISSUE TITLE
Separate audit trackability from permissibility

### ISSUE THREAD

**Issue by RobinIsTheBird** [OpenTreeMap/otm-core#2825]
This issue splits out of #2176 : Create non-field permissions...

Once instance-level permissions are in place, permission is meaningless on certain fields, notably `Tree.plot`, and `id`, `readonly` and `geom` fields on all relevant models. However, we still want to track them in the audit trail in case of errors or hacks.

`treemap.audit.Authorizable`, which is chiefly though not solely responsible for permissioning, is already separate from `treemap.audit.Auditable`, both of which are based on `treemap.audit.UserTrackable`.

`UserTrackable` has a `do_not_track` list.

We could add a `skip_authorization` list to `Authorizable`. A number of other modules would be affected.

**Comment by RickMohr** [comment]
Looks good. I'd remove `readonly` from the list, since if we implement it we will want a field permission.

**Comment by RobinIsTheBird** [comment]
@RickMohr it's easy enough to put back. While it's unavailable, I think it should be hidden from the user, and would prefer not to put 2 criteria for hiding from the user into the Roles page.

**Comment by RickMohr** [comment]
Fair enough. Have a good sleep, `readonly`.
