### ISSUE TITLE
Use improved i-Tree region data

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#2845]
Currently our i-Tree region boundaries fail to cover many coastal areas. Load improved boundaries from fileshare shapefile `projects/Azavea_OpenTreeMap/data/iTree_climate_zone_from_ForestService`

**Comment by hadleystein1** [comment]
+1 Openlands (https://www.opentreemap.org/openlands/map/). All but 12 trees have species and diameter information.

![screen shot 2016-12-22 at 10 58 33 am](https://cloud.githubusercontent.com/assets/15219245/21431651/1dcb9888-c836-11e6-9209-0af8f33b12f5.png)
