### ISSUE TITLE
Combine permissions for adding tree/plot. Also for deleting tree/plot.

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#2848]
We now have separate permissions for "Can add tree" and "Can add plot". I think we should combine them, for several reasons:
1. It's simpler for users if we have fewer permissions
2. I don't think any users want the "cross cases" -- letting people add trees but not plots, or vice versa
3. The cross cases don't work right currently:
    * If you're allowed to create plots but not trees we let you start creating but fail on the "Done" step
    * If you're allowed to create trees but not plots the "Edit" button is disabled on the detail page and there's no way to create a tree.

Likewise for "Can delete tree" and "Can delete plot". I don't think any users want the "cross cases" -- letting people delete trees but not plots, or vice versa.

(I also suspect nobody would want the cross case of letting people add/delete trees but not tree photos. Though the converse might possibly be useful -- letting people add/delete tree photos but not trees.)

**Comment by dboyer** [comment]
There is a possible use case for allowing people to add plots but not trees. We've heard from several clients and potential clients about the ability for users to indicate a potential planting location. A map admin or editor would then add a tree to that location during a planting event. 

The TreeKIT surveying wheel method is also intended to create an accurate map of planting locations where those locations would become read-only but users could add trees to the plots.

**Comment by RickMohr** [comment]
OK, if we're keeping this I'll enter several other issues instead.

**Comment by RickMohr** [comment]
Closing since it sounds like we want separate permissions for adding trees and adding plots. See #2852, #2856.

**Comment by jwalgran** [comment]
Closing because the previous comment says "Closing since..."
