### ISSUE TITLE
Quick Edit button switches to edit mode even when the user is not logged in

### ISSUE THREAD

**Issue by maurizi** [OpenTreeMap/otm-core#2897]
Steps to reproduce:
 - On the map page, click on a planting site when not logged in
 - Click "Quick Edit" in the sidebar
 - A window will popup asking if the user is sure they want to leave, and the form is switched to edit mode

What should happen:
 After clicking "Quick Edit" when not logged in, the user should be redirected to the login page.  No modal should appear asking the user if they wish to leave the page, and the form should not switch to edit mode.

**Comment by RobinIsTheBird** [comment]
Blocked until I can get a second pair of developer eyes on the problem.
