### ISSUE TITLE
ID field names not consistent (UI vs. import/export headers)

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#2978]
We have a policy of consistent field names -- a field's name should be the same in import/export headers and in the UI.

Currently that's not true for ID fields. We call them "Number" in the UI (e.g. "Tree Number", "Resource Number") but "ID" in import/export headers (e.g. "Planting Site ID").

I think we should standardize on either "ID" or "Number". Opinions? @dboyer, @hadleystein1, @jmorrison1847?

**Comment by hadleystein1** [comment]
I vote "Number."

Custom Id leaves room for non-number identification schemes (this assumes "Custom Id" is a text field not an integer field, which now I am realizing I do not know), but for the numbers that we assign, "Number" is more literal than "ID."

**Comment by RickMohr** [comment]
Another wrinkle -- the external link feature currently uses "id" (`#{tree.id}`, `#{planting_site.id}`).

**Comment by hadleystein1** [comment]
@RickMohr Good point. I would then vote to change those to {tree.number} and {planting_site.number}. 

To my knowledge, we have not had any clients report confusion. Tampa may be the exception. @jmorrison1847 can chime in if that's incorrect.
