### ISSUE TITLE
Add endpoint for saving a user-drawn, anonymous boundary

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#2992]
To support filtering map features by a user-drawn area, we have decided to store the geometry in the database and reference it by auto-generated ID in filter statements.

Our tiler and ecobenefit services already support filtering by boundaries saved to the database and referenced by ID. Part of resolving this issue involves research which of these two implementations is preferable:

1) Add an `is_ad_hoc` column to the existing boundary table, store user-drawn geometries the existing table with the new column set to `True`, and modify code that loads and displays named boundaries to ignore the user-drawn boundaries.

2) Store user-drawn geometries in a separate table and modify the filter syntax, tiler, and ecobenefit services to read from this table.

If we opt to create a new table, we will want the following attributes

```
geometry (multipolygon)
created_at (datetime, autogenerated)
```

The endpoint should accept a POST request with a GeoJSON argument or body, save the geometry, and return the database ID in a JSON response

```json
{ "id": 200 }
```

Anonymous users should be able to search by user-drawn geometry, so this endpoint must not be authenticated.

**Comment by RobinIsTheBird** [comment]
@jwalgran, @maurizi, and @RickMohr, If we use the `treemap_boundary` table, could we just use `category='ad hoc' instead of adding an `is_ad_hoc` boolean column?

**Comment by jwalgran** [comment]
Yes, we could use Category 

Pro:
- Ad-hoc boundaries don't have categories, so that field would be unused anyway.
Con: 
- Using a "Magic" constant in the data instead of an explicit "flag" column in the table schema.

In either case, we need to change the code that assigns boundaries to instances to ignore any ad-hoc boundaries. 

If storing ad-hoc boundaries in the existing boundaries is preferable to putting them in a separate table, I have a slight preference for adding an explicit `is_ad_hoc` column.

**Comment by RobinIsTheBird** [comment]
Using the same `treemap_boundary` table as other boundaries, all we would have to change are:
- otm-core `Instance#boundary_thumbprint` property, to exclude ad hoc boundaries
- otm-addons `cloud_management.instance._init_instance` where it sets `instance.boundaries`, again to exclude ad hoc boundaries.

I recommend keeping ad hoc boundaries in the `treemap_boundary` table, and designating them by an empty `name` and empty `category`.
