### ISSUE TITLE
Create a `works_management` Django application with a models file

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#2996]
#### Models

- `WorkOrder`
  - `Auditable`, so we track state changes. Not `Authorizable`.
  - Has many `Task`s
  - Fields
     - FK to `Instance`
     - created_at (date, non-null, autogenerated)
     - created_by (non-null FK to `User`)
     - updated_at (date, non-null)
     - name (non-null)
- `Team`
  - Fields
    - Non-null FK to `Instance`
    - name (non-null)
- `Task`
  - `Auditable` so we track state changes. Not `Authorizable`.
  - `UDFModel` to allow custom fields
  - Fields
    - Non-null FK to `Instance`
    - Non-null FK to `MapFeature`
    - Nullable FK to `WorkOrder`
    - Nullable FK to `Team`
    - status (non-null choices: `Requested` (default), `Scheduled`, `Completed`, `Canceled`
    - created_at (date, non-null, autogenerated)
    - created_by (non-null FK to `User`)
    - updated_at (date, non-null)
    - requested_date (date without time)
    - scheduled_date (date without time)
    - closed_date (date without time)
    - office_notes (nullable text)
    - field_notes (nullable text)
  - "Canned" custom field
    - Action
      - Can’t delete field
      - Set of fixed choices that cannot be deleted (plant tree, remove tree, etc.) but also allows user-defined choices.

#### Notes

- Use `ugettext_lazy` for `Task.status` choices so they can be translated. Store the selected choice as a number to ease renaming and translation.
- If a `Task` is updated, and the `Task` has a `WorkOrder`, set the value of `updated_at` on both the `WorkOrder` and the `Task`.

**Comment by RickMohr** [comment]
@RobinIsTheBird proposes that `requested_on`, `scheduled_on`, and `closed_on` will be clearer than `requested_date`, `scheduled_date`, and `closed_date`.
