### ISSUE TITLE
Last Edited By returns null on many but not all maps - need to run update script on production

### ISSUE THREAD

**Issue by jmorrison1847** [OpenTreeMap/otm-core#2997]
On MyTreeBR, if you go under the advanced search tab > General > "Last Updated By" and select a username (in this case, `CooperBRGreen`) the subsequent search returns no results:
1. 
<img width="1392" alt="screen shot 2017-02-20 at 12 22 11 pm" src="https://cloud.githubusercontent.com/assets/12401491/23135600/45363472-f767-11e6-998f-d89305ecc66f.png">
2.
<img width="1392" alt="screen shot 2017-02-20 at 12 22 47 pm" src="https://cloud.githubusercontent.com/assets/12401491/23135625/56696fe8-f767-11e6-8621-3200d39a5548.png">

CooperBRGreen edits the map very frequently, however, as you can see from the edits page: https://www.opentreemap.org/mytreebr/edits/.

This problem is common but not consistent across all maps. For instance, it's possible to search for user `tmikel` on Kawarth Lakes (www.opentreemap.org/kawarthalakes) and return all of the trees he last updated:
<img width="1392" alt="screen shot 2017-02-20 at 12 28 15 pm" src="https://cloud.githubusercontent.com/assets/12401491/23135849/28f4c9ee-f768-11e6-9d71-1eeb6669e51c.png">

**Comment by jmorrison1847** [comment]
I just noticed--I am the map owner on Kawartha Lakes. So it's a permissions issue--only the map owner is allowed to make that search.

**Comment by maurizi** [comment]
There isn't supposed to be any permission checking happening for the Last Updated By search.

**Comment by RickMohr** [comment]
That `tmikel` search succeeds for me on Kawartha Lakes.

**Comment by jmorrison1847** [comment]
Could it be maps created before/after that feature was implemented? Older maps don't seem to work (e.g. `phillytreemap` and `renotrees`) whereas newer maps do (e.g. `tampa`, `kawarthalakes`).

**Comment by jwalgran** [comment]
I searched our team chat and did not find anyone mentioning that the backfill command `set_mapfeature_updated_by`, was run on production. This example map feature supports that explanation.

![screen shot 2017-02-20 at 1 51 42 pm](https://cloud.githubusercontent.com/assets/17363/23141653/133b2cb2-f775-11e6-9c2b-a7ba2faa6e30.png)

**Comment by RickMohr** [comment]
Running the update script fixed the main issue, but there's still a caching issue -- 
If someone did a "last updated by" search before the update they'll see cached tiles that don't show the updated results.
Workaround is to zoom in or edit the map in some way.
If we do a script like this again we should remember to update the `universal_rev` for all instances.
