### ISSUE TITLE
Custom area filters are problematic with current search UX

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#3005]
Currently OTM search has two steps: 1) specify filters, and 2) click "Search". There's room for confusion in the "limbo" state where you've done 1) but not yet 2). 

That hasn't been a big problem so far with field filters, but it will be a problem with custom area filters.

(The current "Spruce Up" design [eliminates the limbo state for field filters](https://marvelapp.com/1e26i93/screen/16004984) by using a modal dialog, but [does not eliminate the limbo state for boundary filters](https://marvelapp.com/1477g8h/screen/16005013).)

Say you've just searched on zip code boundary 19119 so your area is displayed. Now you click "Draw an area". We can't clear your old area yet, because it's part of the current search. But you might be drawing in the same place so you'd see two polygons at once. 

We could:
* Hide the boundary while you're drawing your polygon
* If you cancel, restore the boundary
* When you finish, show the polygon with special styling that says "I exist but you haven't clicked 'Search' yet"
* If you click the "X" to remove your custom area, restore the boundary
* If you click "Search", your custom area is finally official

This would be simpler if completing your polygon caused an immediate search, eliminating the limbo state for custom area filters. Scott's recent polygon-drawing design actually suggests no limbo state, since "CUSTOM AREA" is displayed as soon as you finish drawing. But it's probably a bad idea to have a limbo state for field filters and boundary filters but no limbo state for custom area filters.

I'm guessing the best solution is to introduce custom area filters only with the rest of "Spruce Up", in a way that eliminates the limbo state for all filters.

Comments welcome. @lederer, @dboyer

**Comment by lederer** [comment]
What if we…

1. Eliminate the limbo state for all filters. 

IIUC, you have to actively select (via click or kb cursor+enter) one of the items in the autocomplete menu anyway, for both field and boundary filters. Clicking [Search] seems redundant and unnecessary.

2. Treat boundary filters and custom filters the same. That is, once you issue the textual search for an area (eg 19119), the location search field looks like [the active custom area field](https://marvelapp.com/1i398c7/screen/24945795), complete with [x] to clear it. 

The implication being you can only have one (boundary or custom) area active at once. In the scenario @RickMohr outlined, you would click [x] to clear the 19119 boundary before you could click the [pencil] to draw a custom area.

Would that work?

**Comment by RickMohr** [comment]
Sounds good @lederer.

Inside the "Search by Location" boundary there should be either a "pencil" icon (iff the box is empty) or an "X" (iff the box contains one or more characters). 

Clicking the "X" will clear the box and perform a search without any location filter.

**Comment by RickMohr** [comment]
To summarize, here's our plan:

When searches happen:
* Location searches will happen immediately, when you choose an autocomplete result in "Search by Location" or complete a custom polygon.
* Species searches will happen immediately when you choose an autocomplete result in "Search by Species".
* Field filters (in "Advanced Search") will be unchanged, requiring you to click "Search".
* Question -- should "Last updated by" searches happen immediately when you choose an autocomplete result?

The "Search by Location" area:
* When no location search is in effect the "Search by Location" input box will contain either a "pencil" icon (if the box is empty) or an "X" (if the box is non-empty). Clicking the "X" clears the box.
* After a successful location search (for an address or named boundary), display the (autocompleted) location text in the "Search by Location" area (with styling used for "CUSTOM AREA"), along with an "X". Clicking the "X" clears the box and performs a search with no location filter.
* So our policy is that before specifying a location search you must first clear any existing location search.

**Comment by lederer** [comment]
That sounds right to me, @RickMohr. Thanks for unpacking the details.

>Question -- should "Last updated by" searches happen immediately when you choose an autocomplete result?

No. One objective of these changes is _predictable_, _sensible_ behavior that's _consistent_ within each search tier (ie, 1. main species+location tier, 2. advanced search tier). Better for the behavior of "Last updated by" to be consistent within its (advanced search) tier — ie, don't trigger search onchange — than consistent with other autocomplete controls across tiers.
