### ISSUE TITLE
Boundary search incorrectly highlights "Advanced"

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#3013]
1. Click the "Search by Location" box
1. Click an autocomplete option

Expected: "Advanced" not highlighted
Actual: "Advanced" highlighted

**Comment by maurizi** [comment]
Duplicate of https://github.com/OpenTreeMap/otm-core/issues/2955 ?

**Comment by RickMohr** [comment]
Sigh. When's the next bug bash day? Closing.
