### ISSUE TITLE
Endpoint to modify anonymous boundary

### ISSUE THREAD

**Issue by RobinIsTheBird** [OpenTreeMap/otm-core#3017]
Modify the anonymous boundary endpoint from #2992 to modify an existing anonymous boundary

**Comment by maurizi** [comment]
I'm not sure if this _is_ something we should do.

It basically comes down to the following:
 1. User does a polygonal search of the Wissahickon neighbourhood on PhillyTreeMap, and bookmarks the page so they can return to it later
 1. User uses their bookmark to see how their search has changed
 2. User then modifies the polygon to include the nearby East Falls neighborhood as well. They do not make a new bookmark
 3. User returns to their bookmark from step 1; Do they see a polygon representing Wissahickon (step 1), or one representing Wissahickon & East Falls (step 3)?

Both options seem valid to me, and option one (modifying a polygon always makes a new anonymous boundary that changes the URL) seems easier to implement.

**Comment by RobinIsTheBird** [comment]
That use would learn pretty quick that if they want a different search, they should start a new search.

This offers a way to correct a not-quite-right polygon without additional db clutter.

**Comment by jwalgran** [comment]
We discussed this when we were designing the feature and opted to not implement a second PUT handler as part of the MVP.
