### ISSUE TITLE
Integrate anonymous boundary endpoint with frontend

### ISSUE THREAD

**Issue by RobinIsTheBird** [OpenTreeMap/otm-core#3018]
- Ajax to the anonymous boundary endpoint from polygon drawing and editing to create and update it
- Update the url to reflect the anonymous boundary id
- Display the boundary when navigating to a url that includes an anonymous boundary id

Blocked on #3017

**Comment by RickMohr** [comment]
I believe this is covered by #2994

**Comment by jwalgran** [comment]
It is covered by #2994
