### ISSUE TITLE
How should we declare protected UDFs?

### ISSUE THREAD

**Issue by kdeloach** [OpenTreeMap/otm-core#3022]
Django models that inherit from `UDFModel` may define custom fields using the `udf_settings` property:

```
class Task(UDFModel):
    udf_settings = {
        'Action': {
            'iscollection': False,
            'defaults': {
                'type': 'choice',
                'choices': [
                    'Plant Tree',
                    'Remove Tree',
                    'Other action',
                ],
            }
        },
    }
```

For Works Management tasks, we want the ability to define "protected" choices (for "actions"), which cannot be deleted. Presumably, these are also protected against renaming. How should we update the `udf_settings` syntax to support this?

Here are some ideas:

1. `isprotected` property

```
udf_settings = {
    'Action': {
        'iscollection': False,
        'isprotected': ['Plant Tree', 'Remove Tree'],
        'defaults': {
            'type': 'choice',
            'choices': [
                'Plant Tree',
                'Remove Tree',
                'Other action',
            ],
        }
    },
}
```

2. Enhance `choices` to support metadata tuples

```
udf_settings = {
    'Action': {
        'iscollection': False,
        'defaults': {
            'type': 'choice',
            'choices': [
                ('Plant Tree', 'protected'),
                ('Remove Tree', 'protected'),
                'Other action',
            ],
        }
    },
}
```

3. Enhance `choices` to support a metadata class

```
udf_settings = {
    'Action': {
        'iscollection': False,
        'defaults': {
            'type': 'choice',
            'choices': [
                UDFSettingsChoice('Plant Tree', can_delete=False),
                UDFSettingsChoice('Remove Tree', can_delete=False),
                'Other action',
            ],
        }
    },
}
```

**Comment by maurizi** [comment]
We don't just want to protect against deleting/renaming of choice fields, but also the field itself (the existing `udf_settings` code does not do this).

With that in mind, here is my preference:
```python
udf_settings = {
    'Action': {
        'iscollection': False,
        'is_protected': True,
        'defaults': {
            'type': 'choice',
            'protected_choices': [
                'Plant Tree',
                'Remove Tree',
            ],
            'choices': [
                'Other action',
            ],
        }
    },
}
```

**Comment by kdeloach** [comment]
Thanks, I hadn't considered that fields and choices both need to be protected. I like how this syntax looks compared to the other proposed options. I'll implement this feature based on Mike's example unless anyone else has a better idea.

**Comment by jwalgran** [comment]
A top level `is_protected` is a good idea and I would expect that having a simple top level boolean will make the "should I show the delete button" logic more clear.

I don't have a strong preference when it comes to defining protected choices in a separate list vs. annotating them and mixing them in with other choices. I suspect that a separate list would be easier to implement.

**Comment by RobinIsTheBird** [comment]
I think @maurizi's proposal is extensible. In the future we could
- protect but allow renaming by adding` 'renamable_choices'` oslt
- additional fields to describe dependencies, e.g. `'incompatible_with'` oslt
- add ranges to numerical types

**Comment by maurizi** [comment]
To play devils advocate: the one downside I can think of to what I suggested is that it prevents mixing the order of protected and unprotected fields.

I think that is OK, because we're protecting delete / remove tree because we want them to be special, so I think its OK that they will always be first in the list.

**Comment by RickMohr** [comment]
Should we build this as part of #2996 or as a separate issue?

**Comment by jwalgran** [comment]
Yes, it is one of the bullet points on #2996.

**Comment by kdeloach** [comment]
Thanks for the feedback!
