### ISSUE TITLE
Stewardship search with date does not include date when searching

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-core#3029]
Tested on staging (testmap0301) in Chrome on a Macbook

1. Add stewardship entries for "watered" (default tree stewardship category) and "pruneddd" (modified tree stewardship category) with several different dates on several different trees
2. Search for trees watered between Feb 26 and March 2
3. Results say 2 trees, 0 empty planting sites
4. No tree dots are highlighted on map
5. Export search results and see that the trees have entries for watered on Jan 11 and Feb 17

I found similar results when searching pruneddd. I tested the above steps on production and did not see the same results.

**Comment by dboyer** [comment]
The issue happens on both tree and planting site stewardship searches.

**Comment by RobinIsTheBird** [comment]
duplicated in Chrome on Ubuntu, same staging treemap.

**Comment by RobinIsTheBird** [comment]
This is not a regression. I easily reproduced it in production.

**Comment by dboyer** [comment]
If it's useful, on production map testmap0301 I saw date based stewardship working successfully as described:

1. Added two trees with a stewardship action of Pruneddd - one on January 30, 2017 and one on February 18, 2017. 

2. Searched tree care with the following terms: I am looking for trees that have been Pruneddd between 1/1/2017 and 1/31/2017.

3. Search results returned one result as expected

4. Changed the date parameters to 1/1/2017 and 3/1/2017

5. Search returned two results as expected

**Comment by RickMohr** [comment]
@dboyer, to make it fail you need to have a Pruneddd entry that is not in the date range and a non-Pruneddd Stewardship entry that is in the date range.

Should return no results, but returns one.

**Comment by jwalgran** [comment]
We decided that this should not block the 2.15.0 release so I removed it from the milestone.

**Comment by RobinIsTheBird** [comment]
@dboyer and @RickMohr, to make it fail, all you need is a Pruneddd entry that is in the date range, and a Watered entry that is not in the date range, on the _same tree_.
