### ISSUE TITLE
Reduce size of handles on polygon for drawing GSI feature

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-core#3030]
Tested on staging in Chrome on a Macbook.

When working on smaller rain gardens or bioswales, the large boxes overlap each other and can be difficult to manipulate.

![screen shot 2017-03-04 at 9 57 53 pm](https://cloud.githubusercontent.com/assets/516764/23584127/a3ae022e-0125-11e7-9d9b-cd7de31409bd.png)

**Comment by RickMohr** [comment]
Those big squares are Leaflet Draw's default icon, but that can be overridden. If somebody (@lederer?) provides a different icon (smaller? not square?) we can use it to replace the big square.

They may have chosen a large-sized default icon to support mobile use. But the situations where we need to create/edit polygons (adding a Bioswale, defining a custom search area, creating a modeling distribution) seem unlikely to be used on mobile.

**Comment by jwalgran** [comment]
If our recently updaded Leaflet supports it then increasing the max zoom beyond the base map resolution may be a simple solution to this problem.

**Comment by lederer** [comment]
Circles like those in the Draw Search Area mocks would be preferable. I'm
OOO today but can whip one up tomorrow, if it can't be done
programmatically in Leaflet.

**Comment by RickMohr** [comment]
Looks like it can all be done with JS and CSS. Working on it...

**Comment by RickMohr** [comment]
@jwalgran, it looks like we can't increase the max zoom until the next release of Leaflet. [`googleMutant`](https://www.npmjs.com/package/leaflet.gridlayer.googlemutant) (the Leaflet plugin we use to display google map tiles) says:

"The `maxNativeZoom` functionality introduced in v0.5.0 requires Leaflet >1.0.3. At the time of this writing, this means "using the master branch of Leaflet".

Currently, increasing the max zoom sort of works -- if you switch to the satellite layer at zoom 21 you will still see it at zoom 22. But if you zoom to 22 and then switch to the satellite layer you won't see it.

**Comment by RickMohr** [comment]
Here's a tiny "Sidewalk Garden" (15 sq ft) at max zoom from `urbanforestmap`, on [production](https://www.opentreemap.org/urbanforestmap/features/2612758) and [staging](https://staging.opentreemap.org/urbanforestmap/features/2612758):

![image](https://cloud.githubusercontent.com/assets/2162993/23622547/1a196898-026d-11e7-95b7-99f097bcd739.png) ![image](https://cloud.githubusercontent.com/assets/2162993/23622685/965c6108-026d-11e7-9942-f362428a2022.png)

I'm inclined to use the original handle size and shape. Some options:

(1) ![image](https://cloud.githubusercontent.com/assets/2162993/23625401/0fc3bede-0277-11e7-907b-083f05f778b4.png) (2) ![image](https://cloud.githubusercontent.com/assets/2162993/23625369/e7771fb6-0276-11e7-8dcd-0d295ea62c7a.png) 
(3) ![image](https://cloud.githubusercontent.com/assets/2162993/23625485/52a7f42c-0277-11e7-8a25-12405f129dee.png) (4) ![image](https://cloud.githubusercontent.com/assets/2162993/23625445/2e12425c-0277-11e7-8360-b2a3e14bb1e9.png)

I lean toward (1). @dboyer? @lederer?

We should definitely keep an eye on Leaflet releases, and increase the max zoom ASAP.

**Comment by jwalgran** [comment]
I like the lighter line weight in options (1) and (3)

The red is a little more visible, but I do not have a strong opinion.

**Comment by dboyer** [comment]
1 is fine with me.

**Comment by lederer** [comment]
1 please!

**Comment by RickMohr** [comment]
Finally got to the bottom of this. Leaflet Draw has different polygon vertex icons for touch screens and non-touch screens, and decides which to use based on Leaflet's `L.Browser.Touch`. But with current browsers and the latest Leaflet release, `L.Browser.Touch` is `true` for a browser that supports touch even when you're using a non-touch device. That's why we get giant vertex icons on desktop devices.

Since for us polygon editing is unlikely to be done via touch, we can tell Leaflet Draw to always use the non-touch icons.

So do we want the upvoted (1), or Leaflet Draw's non-touch default (5):

(1) ![image](https://cloud.githubusercontent.com/assets/2162993/23625401/0fc3bede-0277-11e7-907b-083f05f778b4.png) (5) ![image](https://cloud.githubusercontent.com/assets/2162993/23661464/d2b5cb00-031a-11e7-99f2-bea20d52e4ea.png)

I lean toward (5).

**Comment by lederer** [comment]
Circles, please, but you can decrease the diameter to match the width of the non-touch default squares.

**Comment by dboyer** [comment]
I'm fairly ambivalent so let's go with what @lederer says.

**Comment by dboyer** [comment]
Looks good when tested on staging.
