### ISSUE TITLE
Date format in export does not match required date format for import

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-core#3035]
Dates export as M/D/YY and the import requires YYYY-MM-DD

**Comment by RickMohr** [comment]
@dboyer, can you provide an example? In the export I tried the dates are YYYY-MM-DD. 

(Is it possible your spreadsheet program was converting them for display? Try opening the CSV in a text editor...)

**Comment by dboyer** [comment]
I think it is a formatting issue with Excel on Mac. I see the correct date format when I open it in TextEdit. Closing this.

**Comment by dboyer** [comment]
Wait, reopening to not confuse the waffle.
