### ISSUE TITLE
International Address Geocode Failure

### ISSUE THREAD

**Issue by jmorrison1847** [OpenTreeMap/otm-core#3038]
I'm curious about what is happening when I search for "Rua de Dona Estefânia, Lisboa, PRT" on the trial map `jfarroios`. If you start typing it out, you get a matched address in the dropdown:
<img width="1388" alt="screen shot 2017-03-06 at 1 19 30 pm" src="https://cloud.githubusercontent.com/assets/12401491/23623966/0e7a9a70-0272-11e7-92d8-1b7b0ba963e8.png">
But it returns no results:
<img width="1258" alt="screen shot 2017-03-06 at 1 19 49 pm" src="https://cloud.githubusercontent.com/assets/12401491/23623976/153daf5a-0272-11e7-9348-49d0f74bb9cc.png">

Is there any way to troubleshoot what is happening when a geocode fails?

**Comment by RickMohr** [comment]
Did you click on the autocomplete?

**Comment by RickMohr** [comment]
Just tried it -- yes you get that failure even clicking on the autocomplete. I'd call that a bug.

**Comment by jmorrison1847** [comment]
I was able to autocomplete a few random streets in other parts of the city, so I think it may be a special/particular bug, not a generalized one for the map.

**Comment by maurizi** [comment]
@jmorrison1847 Was this fixed by the changes to support unicode addresses?

**Comment by jmorrison1847** [comment]
Yes it does! https://www.opentreemap.org/jfarroios/map/?z=18/38.73475/-9.14154
