### ISSUE TITLE
Importer: ignore blank rows

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#3040]
We've had at least two cases where uploading a giant CSV containing mostly blank rows took forever, hogging resources along the way.

We could reduce the impact of that kind of mistake by [ignoring blank rows here](https://github.com/OpenTreeMap/otm-core/tree/develop/opentreemap/importer/tasks.py#L53).

Should be quick to implement.

**Comment by jwalgran** [comment]
@RickMohr the link in the issue description is broken.

@hadleystein1 you recently ran into this problem. Could you please attach the CSV so that we could use it as a real world example for testing.

**Comment by RickMohr** [comment]
Link fixed
