### ISSUE TITLE
Add a priority field to the Works Management Task model

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#3048]
- `priority` should be an integer choice field with a fixed set of choices. 
- We want the choices to be in order so that we can use a `min` database function to easily aggregate tasks and find the most urgent priority.
- The choice labels should be High, Medium, Low

**Comment by jmorrison1847** [comment]
I vote for replacing "Normal" with "Routine" since I see that word a lot in inventories that I look at. But the general thought of 3 buckets makes total sense to me.

**Comment by jmorrison1847** [comment]
Sorry--missed the "Comment" button and accidentally closed it.

**Comment by RickMohr** [comment]
I think we should consider "High", "Medium", and "Low" because they're easy to understand and give customers more flexibility in how to categorize things. For example I might want to prioritize a task as "High" priority but I might not consider it "Urgent".

**Comment by dboyer** [comment]
I also agree that we should stick with as general as possible and would prefer High, Medium, Low or 1, 2, 3 rather than something like Urgent or Immediate.

**Comment by jwalgran** [comment]
There is a consensus around High, Medium, and Low, so I updated the issue description.
