### ISSUE TITLE
Add endpoint to create Tasks from a map feature search

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#3051]
Accepts search JSON to define the map features for which `Tasks` will be created along with field values collected from the modal form (#3050)

The endpoint will associate the created `Task`s with either a new `WorkOrder` or an existing work order.

`search.py` can already convert query JSON to a result set.

Coordinate the development of this with #3050 to make sure the data collected by the form matches what the endpoint expects. It is not strictly blocked by #3050 because the endpoint can be unit tested.

**Comment by RobinIsTheBird** [comment]
I assume that only plots (with or without trees) are considered, and stormwater resources are ignored. Yes?

**Comment by jwalgran** [comment]
We decided to exclude non-plot map features from the work order process.
