### ISSUE TITLE
Add WM Task custom fields to existing instances

### ISSUE THREAD

**Issue by kdeloach** [OpenTreeMap/otm-core#3056]
Create migration to add the WM Task custom fields to all existing instances. These fields should also be added to newly created instances.

**Comment by jwalgran** [comment]
I labeled this as "question" because we will want to review how adding stormwater features to an instance works and adopt a consistent behavior if it makes sense.

**Comment by kdeloach** [comment]
I would also prefer to add a new checkbox in super_admin to enable this feature. Until we do this, adding WM custom fields to an instance (for development & testing) will be a manual process.
