### ISSUE TITLE
Add updated_by field to WorkOrder and Task models

### ISSUE THREAD

**Issue by kdeloach** [OpenTreeMap/otm-core#3059]
Reference `MapFeature` to determine how to implement these changes.

* [ ] Add `updated_by` field to `WorkOrder` and `Task` models
* [ ] Ensure these values are updated in `save_with_user`

**Comment by RobinIsTheBird** [comment]
also `updated_at`, and reference it for `created_by` and `created_at` as well.

**Comment by kdeloach** [comment]
Feel free to update the description if I missed anything. The `created_by`, `created_at`, and `updated_at` fields should already exist.
