### ISSUE TITLE
Polygonal search tool should not be visible on mobile

### ISSUE THREAD

**Issue by maurizi** [OpenTreeMap/otm-core#3063]
It isn't visible on the map view, but is on the advanced search view.

![localhost-6060-phillytreemap-map--z 18-40 02121--75 20617 nexus 5x](https://cloud.githubusercontent.com/assets/4432106/24050675/fb351426-0b05-11e7-96fd-d03a1c4ab4e2.png)

**Comment by RickMohr** [comment]
I don't see this problem on staging or on my machine. @maurizi could you please double check on your browser?

**Comment by maurizi** [comment]
I can reproduce this on both Firefox and Chrome in responsive design mode (and also on Chrome for Android)
 1. Go to staging.opentreemap.org/phillytreemap/map
 2. Start responsive design mode
 2. Open the advanced search menu and observe that there is no icon
1. Refresh the page
 2. Open the advanced search menu and observe that there is a search icon

It is only hidden if the page started out big and then was shrunk... very odd

**Comment by RobinIsTheBird** [comment]
In this case, does "mobile" mean `$screen-xs    : "(max-width: 767px)";` or `$screen-ltmd  : "(max-width: 991px)";`?

**Comment by maurizi** [comment]
`$screen-xs` - thats the cut-off where we show the advanced search as a fullscreen view instead of in dropdown menus
