### ISSUE TITLE
How can I change initial zoom of the map to be greater?

### ISSUE THREAD

**Issue by michalstepniewski** [OpenTreeMap/otm-core#3065]
How can I change initial zoom of the map to be greater?

**Comment by RickMohr** [comment]
Initial map zoom is chosen to display all trees. Sometimes a single mistakenly-placed tree can cause an unwanted low zoom. Currently there is no option to specify the initial zoom.

The mailing list opentreemap-user@googlegroups.com is a good place for questions like this.
