### ISSUE TITLE
Selected species changes after clicking "Search"

### ISSUE THREAD

**Issue by RobinIsTheBird** [OpenTreeMap/otm-core#3080]
This happens on staging. I haven't boiled down the minimum number of steps to reproduce it.

Create a map with two fir [Abies] trees in the same zip code, and search for fir [Abies].

Draw a polygon that includes one or both.
Keep changing the polygon to include both and then only one and back. Refresh between changes.

Trash the polygon, and search for the zip code that includes both fir trees.

The species part of the search might switch to Balsam fir [Abies balsamea]!

If it doesn't try searching for an adjacent zip code that doesn't have any fir [Abies] trees, and then back to the original zip code.

Eventually, the species search switches.

Experienced on https://staging.opentreemap.org/rgs-170223-01/map/?z=12/42.7456/-73.5918&q=%7B%22species.id%22%3A%7B%22IS%22%3A%22442381%22%7D%2C%22mapFeature.geom%22%3A%7B%22IN_BOUNDARY%22%3A%223992%22%7D%7D

**Comment by RobinIsTheBird** [comment]
@dboyer, I think this bug should be high.

**Comment by dboyer** [comment]
I switched this to high. I recreated the bug by:

1. Creating a new map
2. Adding two trees with a generic Abies species one block away from each other
3. Typed fir in the species search and then clicked on the Fir/Abies option which was fifth in the drop-down menu
4. If I manually clicked the Search button, the search species changed to Balsam fir

**Comment by jwalgran** [comment]
Another set of reproduction steps from @hadleystein1 

---

Step 1: Search for Norway Maple and select it: https://www.opentreemap.org/arlington/map/.
Step 2: Click Advanced and set Diameter to 0 to 4 inches.
Step 3: Press Search

After pressing Search, the species switches from Norway Maple to Norway Maple Schwedler. The user must go back and reselect Norway Maple again (after setting the diameter parameters) to get the desired search results.

**Comment by jwalgran** [comment]
It looks like the species changes to the first item in the list.
- If you don't search for a species and just pick one using the mouse,  the selected species reverts to the first one in the list.
- If you search for a species the the selected species reverts to  the first item in the matching results list.

**Comment by jwalgran** [comment]
I was able to reproduce this just by selecting a species other than the first one in the list  and clicking "Search"
