### ISSUE TITLE
Replying to comment posts on last comment

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-core#3084]
This is on production

1. Add a comment
2. Add a second comment
3. Click reply on the first comment
4. Enter a comment and click Post
5. Comment appears on a thread for the second comment rather than the first

**Comment by RobinIsTheBird** [comment]
The problem is on the backend

**Comment by dboyer** [comment]
I'm fine with blocking this and updating django-threadedcomments as part of our general python dependency updates to see if that solves the issue.

**Comment by jwalgran** [comment]
The bug persists after updating to the latest versions of our comment libraries https://github.com/OpenTreeMap/otm-core/commit/bbecd2a2d39160e93816670c2d587e0a8e016e5e
