### ISSUE TITLE
Searching by anonymous boundary fails when using an incognito/private browser

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#3093]
When logged out of the application, POSTing to `/anonymous-boundary/` returns 403 Forbidden.

I have been able to replicate this on all browserstack.com browsers I have tried, and on multiple browsers in incognito/private mode.

**Comment by RickMohr** [comment]
For me, searching `phillytreemap` with a custom area works on staging when logged out:

https://staging.opentreemap.org/phillytreemap/map/?z=9/39.8570/-74.7839&q=%7B%22mapFeature.geom%22%3A%7B%22IN_BOUNDARY%22%3A%2241097%22%7D%7D

**Comment by dboyer** [comment]
Yes, searching when logged out seems to work. It doesn't work in incognito mode though.

**Comment by RickMohr** [comment]
It's a CSRF token issue. 
The Django `CsrfViewMiddleware` [is rejecting the request here](https://github.com/django/django/blob/master/django/middleware/csrf.py#L312)

One solution [here](http://stackoverflow.com/questions/18557196/tastypie-csrftoken-not-set-in-incognito-mode)

**Comment by maurizi** [comment]
We could also mark view as [CSRF exempt](https://docs.djangoproject.com/en/1.10/ref/csrf/#django.views.decorators.csrf.csrf_exempt).

**Comment by RickMohr** [comment]
Correction, the middleware rejection is because (no CSRF token is found](https://github.com/django/django/blob/stable/1.8.x/django/middleware/csrf.py#L114)
