### ISSUE TITLE
Update Django to 1.11

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#3112]
Also upgrade any `django-*` packages if necessary for 1.11 compatibility

**Comment by jwalgran** [comment]
We have an existing Django upgrade issue with some commentary (https://github.com/OpenTreeMap/otm-core/issues/2724) that also links to our major blocking issue https://github.com/OpenTreeMap/otm-core/issues/1968. 

I added this issue's description to the description of #2724
