### ISSUE TITLE
Make important updates to python dependencies

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#3113]
Look at our list of [updates on requires.io](https://requires.io/github/OpenTreeMap/otm-core/requirements/?branch=develop), and apply any that seem important (e.g. “insecure”)

**Comment by RobinIsTheBird** [comment]
As of 6/1/17, only `django` and `Pillow` are shown on [updates on requires.io](https://requires.io/github/OpenTreeMap/otm-core/requirements/?branch=develop) as out of date.

`Pillow` is only used by `django/core/files/images.py`, which is not imported or used by the app, or by anything in `dist-packages`.

I think it can be ignored until we update `django`.

**Comment by maurizi** [comment]
@RobinIsTheBird `Pillow` is a replacement for `PIL`, and continues to use that name as the name of the Python module.  You will find imports from `PIL` in several places in the codebase.

**Comment by RobinIsTheBird** [comment]
Should happen after we update django or in tandem.

**Comment by RobinIsTheBird** [comment]
Must update `django-threadedcomments` in order to unblock [Replying to comment posts on last comment￼](https://github.com/OpenTreeMap/otm-core/issues/3084).
