### ISSUE TITLE
Search for latreemap Alerts

### ISSUE THREAD

**Issue by RobinIsTheBird** [OpenTreeMap/otm-core#3118]
If Mobile responsive mode is ever to replace the mobile apps, it should include search for latreemap alerts.

@jwalgran, @dboyer, @maurizi, if terminating the mobile apps ever becomes a priority, remember to revisit this.

**Comment by jwalgran** [comment]
I see alert searching working on the web for small screen sizes.

<img width="337" alt="screen shot 2017-04-21 at 8 32 38 am" src="https://cloud.githubusercontent.com/assets/17363/25284831/205c0372-266d-11e7-9350-8136c53e1d8d.png">

Is there some other aspect of searching for alerts that is not implemented for small screen sizes?

**Comment by RobinIsTheBird** [comment]
Hmm, I wrote the issue based on reading the code, which deals specifically with alerts for mobile. There must be other code that deals with it generically. I'll close the issue.
