### ISSUE TITLE
NPM build error Cannot resolve module 'leaflet.gridlayer.googlemutant'

### ISSUE THREAD

**Issue by monroem** [OpenTreeMap/otm-core#3136]
Hi,
It is almost build successfully except one more error.
Please let me know how to fix this error.

Thank You
[NPM Build errors.txt](https://github.com/OpenTreeMap/otm-core/files/1020518/NPM.Build.errors.txt)

**Comment by maurizi** [comment]
An error like this usually indicates that not all JS dependencies are installed.
If you run `npm install`, and then try running ` webpack --config webpack.prod.config.js` again is the error resolved?

**Comment by monroem** [comment]
I think I'm all set with this issue.
