### ISSUE TITLE
Popup showing geocode results should have a "Close" button

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#321]
You get a popup when an address search returns more than one result. Various user actions close the popup, but those may not be obvious to users. A close button is very obvious.

**Comment by RobinIsTheBird** [comment]
Does this refer to the popup you get when you click on a tree or a planting site on the map?

If so, is the "x" in the upper right corner sufficient to close this bug?

**Comment by maurizi** [comment]
@RobinIsTheBird No, it refers to the popup you see when doing an address search (geocoding) and get an ambiguous result.

**Comment by RobinIsTheBird** [comment]
I think the [ OK ] button and the "x" in the upper right of the alert it now pops up are obvious ways to dismiss the alert.

**Comment by RobinIsTheBird** [comment]
Okay, the way to incur ambiguous results is to go to `phillytreemap` and enter "1345 Susquehanna Ave, Philadelphia PA" into the search by location.

This results in a tooltip offering a choice between E and W Susquehanna Ave, in zips 19125 and 19122 respectively. Clicking on either address in the tooltip searches for that specific address, but the hover feedback is too subtle - you might not be able to notice it.

So yes, it ought to have a close button (at least an "x" in the upper right), _and_ hovering over a choice should provide more pronounced feedback.
