### ISSUE TITLE
Date filter on Tree Care advanced search behaving strangely

### ISSUE THREAD

**Issue by jmorrison1847** [OpenTreeMap/otm-core#3245]
![apr-10-2018 19-02-07](https://user-images.githubusercontent.com/12401491/38588054-dfec9292-3cf1-11e8-93e7-71ba11fe9a52.gif)
When you update the date filter for the terminal date, it changes the original date. You can test it out on https://www.opentreemap.org/greenprintmaps/map/.

**Comment by jmorrison1847** [comment]
Seems to be the same for all maps

**Comment by dboyer** [comment]
I am also seeing this issue. It renders the feature fairly unusable so it would be helpful to get in a fix.
