### ISSUE TITLE
Increase contrast between green and brown dots on map

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-core#3251]
A user reported that the contrast between green and brown dots on the map is slight enough that individuals with limited ability to see color cannot distinguish between the dot types.

**Comment by lederer** [comment]
Green generally appears brown to colorblind users, so we'll need to change the planting space color. 

Let's try these:

Tree fill: `#8BAA3C`
Tree stroke: `#A5BF5B`

Planting space fill: `#E1C6FF`
Planting space stroke: `#D4B5F9`
