### ISSUE TITLE
Django Admin fails when updating/creating some tables

### ISSUE THREAD

**Issue by mauriciopasquier** [OpenTreeMap/otm-core#3272]
For example, it fails with

    TypeError at /admin/treemap/species/add/
    all calls to full clean must be done via 'full_clean_with_user'

When creating or updating a species. It fails with

    ValueError at /admin/treemap/instance/1/change/
    Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

When I simply open an instance and save it without changing any data.

Is there any other way to edit this kind of data? I mean for power users of the system, for example.

**Comment by jwalgran** [comment]
OpenTreeMap has auditing and other features that make it incompatible with the Django admin. Instances must be configured either through the `/{url_name}/management` pages or via the Django shell.

**Comment by mauriciopasquier** [comment]
Thanks for the promptly reply! Then I guess if I need to change a species name I have to do it from shell? Because other than importing, I can't find a way to do it from `/{url_name}/management`.

Sorry if it is obvious and I'm not seeing it.

**Comment by jwalgran** [comment]
That is correct. There is no admin UI for changing species name so you must use the shell.
