### ISSUE TITLE
Prevent multi-clicking submit buttons by disabling them

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#336]

**Comment by RobinIsTheBird** [comment]
Having trouble finding a form where submission takes long enough on staging that this is a problem.

**Comment by RickMohr** [comment]
I would close this. Since this was entered we've fixed many such issues, and it's not specific enough to act on.

**Comment by RobinIsTheBird** [comment]
What @RickMohr said.
