### ISSUE TITLE
Set default advanced searches

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-core#359]
Diameter - input format is two boxes that allow numbers with decimals

Last Update - Should check for updates on both the tree and plot. I'm fine with either two boxes where users can enter dates or a single box where they enter a range. Whether it's manually entered or a calendar widget is also up to you. 

Last Updated By - text box that checks against user names 

Planting Date - Should be the same date behavior as last update 

Missing Data - list species and diameter with a check box by each

**Comment by maurizi** [comment]
Since the only thing remaining to support is last updated by, this issue has been superseded by https://github.com/OpenTreeMap/otm-tiler/issues/24 and https://github.com/OpenTreeMap/otm-core/issues/388
