### ISSUE TITLE
Allow filtering map features / ecobenefits by last updated by (user)

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-core#388]
This is just for the UI - the backend is a separate feature

The username input field should be an autocomplete that allows for searching by username.

**Comment by RobinIsTheBird** [comment]
Blocked by https://github.com/OpenTreeMap/otm-core/issues/2863

**Comment by RobinIsTheBird** [comment]
Counting users per instance via
```
users_per_instance = Instance.objects\
    .annotate(num_users=Count('instanceuser'))\
    .order_by('-num_users','url_name')
for upi in users_per_instance[:20]:
    print('{} {}'.format(upi.num_users, upi.url_name))
```
we see
```
1161 phillytreemap
742 latreemap
357 treefolksaustin
```
then four between 100 and 200, and the rest less than 100.

Imo the search view should prefetch N, and fetch the rest dynamically. Then the questions become what is N, and which N to fetch if there are more than that - probably the first N ordered by `username`.

I'll profile prefetching `phillytreemap`'s thousand plus users and see whether it's worth the extra complexity of round-trip searching.

**Comment by RickMohr** [comment]
Seems like it would be simpler to always prefetch or never prefetch rather than needing to handle the case of a partial prefetch. If `phillytreemap` works fine with prefetch, great. And if not, performance without prefetch might be fine for this feature.

**Comment by maurizi** [comment]
> Seems like it would be simpler to always prefetch or never prefetch rather than needing to handle the case of a partial prefetch.

Agreed, I don't think its worth from a code-complexity standpoint to do a partial prefetch.

Since we expect the user list to be invalidated fairly frequently (certainly more so than species or boundaries), we don't derive as much value from prefetching it, since it won't be cached all that often.

**Comment by RobinIsTheBird** [comment]
How long does a user typically stay on the map page in the web browser? I doubt if the users are added so frequently that it would invalidate the prefetch on page enter very often. And if the seeker is looking for changes from a new user, they probably have an idea that the new user just joined, and would think of doing a page refresh.

The code from #2873 is designed for the round trip per search paradigm.

What say I write an alternate endpoint for prefetch and try it with phillytreemap?

This feature will not be ready in time for tomorrow's RRP in any case, regrettably.

**Comment by RickMohr** [comment]
I'd be inclined to build it without prefetch first and see how it performs. If it's fine we save ourselves the time of implementing the prefetch.

**Comment by maurizi** [comment]
From our Slack discussion:
> rschaufler 11:54 AM
> The frontend without prefetch is messy. I feel like implementing prefetch is simpler.otmTypeahead.js does enough for you that I want to use it, but it doesn't appear to support round-trip-per-query except for geocoding. I'd have to modify it as well as add search-specific JS to use it, but am anxious about breaking other things in the process.

> mmaurizi 11:58 AM
> That was the intention of the card - to modify `otmTypeahead.js` to support round-trip-per-query for things that aren't geocoding
> It is some work to do so, but there is _also_ work involved with supporting prefetch for user searching in a performant way
> We'd want to cache the list, and ensure that we don't exceed the cache size and have a way to bust the cache
> otherwise we'll be loading a user list for every page load, for a rather niche feature
> we ran into caching issues with the species and boundary autocomplete lists, where the typeaheads stopped working once you had too many prefetched items cached in local storage
> Which was caused by caching separate lists per instance - so on a developer machine the cache would quickly fill up
