### ISSUE TITLE
clicking a tree should modify window.location.hash

### ISSUE THREAD

**Issue by steventlamb** [OpenTreeMap/otm-core#555]
We may not have a need for a full-blown stateful single-page app a la `Backbone.Hashmodels`, but we should consider having each tree map click event modify the hash to contain the plot ID, and when navigating to that url, that tree's infowindow is activated. This will make redirecting (login) URLS automagically work, and can support later features like "View this plot on my tree map","jump to trees near this one", etc.

@jwalgran and I discussed the need for an AJAX login feature that would maybe make this unnecessary.

**Comment by maurizi** [comment]
Superseded by https://github.com/OpenTreeMap/otm-core/issues/833
