### ISSUE TITLE
When upgrading from Leaflet 0.6.4, resolve source code patch

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#776]
When you select a tree and click "Edit Details" on the sidebar, Leaflet crashes in `_movePopup` (src/layer/marker/Marker.Popup.js).

I applied the fix suggested in https://github.com/Leaflet/Leaflet/issues/1983 --
a Leaflet developer's comment suggests the issue is resolved in master, but the suggested fix doesn't appear there and there's no link to the actual fix.

So when we upgrade Leaflet, check if the issue is fixed by running this plunker (modified from the one in the above issue) with the new version of Leaflet:

http://plnkr.co/edit/oF4g3M

If the plunker works, just use the new Leaflet. If not, look deeper and consider reapplying the fix.

**Comment by jwalgran** [comment]
Leaflet 1.0 was released today.
