### ISSUE TITLE
Styling needed on diameter calculator 

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-core#872]
From @RickMohr 

The diameter calculator (seen in Quick Edit and elsewhere) needs some styling help:
* There's extra space below "Total Trunk Diameter"
* Should the "Diameter" and "Circumference" headers be black when everything else is gray?
* The "Combined Diameter" message that shows up when you add multiple trunks may have the wrong font, and needs to play in the spacing game

**Comment by jwalgran** [comment]
I believe the current layout looks good.

<img width="343" alt="screen shot 2016-03-31 at 9 18 53 am" src="https://cloud.githubusercontent.com/assets/17363/14182778/c1a01c04-f721-11e5-8ae1-ef227d36705d.png">
