### ISSUE TITLE
Draw your own polygons for custom search boundaries

### ISSUE THREAD

**Issue by andrewbt** [OpenTreeMap/otm-core#917]
It would be a cool feature to select an arbitrary geographic area and determine the eco benefits of the trees there / do other types of searches. So, kind of like our current neighborhood or zip code level searching except using something like Leaflet.draw to let the user select a custom area.

https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-draw/

**Comment by maurizi** [comment]
This is actually happening! And we opened issues for it, so I'm closing this one as a duplicate.

**Comment by andrewbt** [comment]
@maurizi 👋  Man, we've been trying to get functionality like this into CARTO for.....ever... Kudos!
