### ISSUE TITLE
Plot Detail Add Tree State problem (cancel cleanup)

### ISSUE THREAD

**Issue by steventlamb** [OpenTreeMap/otm-core#943]
1) Enter a plot detail for a plot that has no tree
2) Click edit
3) Click Add Tree
4) Click cancel (not cancel add tree, cancel editing the plot)
5) *bug:* there are empty tree details in the summary.
6) Refresh page
7) Back to normal (no tree info).

**Comment by jwalgran** [comment]
I cannot reproduce this in the latest production release.
