### ISSUE TITLE
grunt --dev mode doesn't build treemap.min.js

### ISSUE THREAD

**Issue by steventlamb** [OpenTreeMap/otm-core#958]
Running

`fab vagrant static:dev_mode=True`

does not reebuild `treemap.min.js`, which is currently required for the ui tests. My JS updates were only being picked up in the unit tests when I run:

`fab vagrant static` (without dev mode, even though I'm definitely doing development!)

This should be handled somehow.

**Comment by maurizi** [comment]
This issue is old (and `fab` is gone) but the problem still remains: UI tests need the minified production bundle, but developers don't want to minify everytime, and don't think to run the production JS build before running UI tests.  I'm not sure if there is a good solution to this.
