### ISSUE TITLE
Inline edit form does not remove species on save, but it is removed in the backend

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#975]
Steps to reproduce

  1. Go to the plot detail page for a plot containing a tree with a species set
  1. Edit
  1. Clear all text from the species field
  1. Save

Expected Result: The species field removed from the read-only view

Actual Result: The species remains on the page, but if you refresh the page, the species is no longer there.

**Comment by RickMohr** [comment]
Problem still exists. Title is correctly updated to "Missing Species" but species info remains in the grid.
